// AUTO-GENERATED — run `bun scripts/import-opencode-themes.ts` to regenerate.
// Source: https://github.com/sst/opencode/tree/dev/packages/ui/src/theme/themes
// License: MIT (sst/opencode)
/* eslint-disable */

import type { AimuxTheme } from '../types'

export const OPENCODE_THEMES: Record<string, AimuxTheme> = {
  'amoled-dark': {
    bg: '#000000',
    displayName: 'AMOLED Dark',
    fg: '#ffffff',
    mode: 'dark',
    name: 'opencode:amoled',
    palette: {
      accent: '#ff4081',
      diffAdd: '#00ff88',
      diffDelete: '#ff1744',
      error: '#ff1744',
      info: '#18ffff',
      ink: '#ffffff',
      neutral: '#000000',
      primary: '#b388ff',
      success: '#00ff88',
      warning: '#ffea00',
    },
  },
  'amoled-light': {
    bg: '#f0f0f0',
    displayName: 'AMOLED Light',
    fg: '#0a0a0a',
    mode: 'light',
    name: 'opencode:amoled',
    palette: {
      accent: '#ff0080',
      diffAdd: '#00e676',
      diffDelete: '#ff1744',
      error: '#ff1744',
      info: '#00b0ff',
      ink: '#0a0a0a',
      neutral: '#f0f0f0',
      primary: '#6200ff',
      success: '#00e676',
      warning: '#ffab00',
    },
  },
  'aura-dark': {
    bg: '#15141b',
    displayName: 'Aura Dark',
    fg: '#edecee',
    mode: 'dark',
    name: 'opencode:aura',
    palette: {
      accent: '#ff6767',
      diffAdd: '#61ffca',
      diffDelete: '#ff6767',
      error: '#ff6767',
      info: '#82e2ff',
      ink: '#edecee',
      neutral: '#15141b',
      primary: '#a277ff',
      success: '#61ffca',
      warning: '#ffca85',
    },
  },
  'aura-light': {
    bg: '#f5f0ff',
    displayName: 'Aura Light',
    fg: '#2d2640',
    mode: 'light',
    name: 'opencode:aura',
    palette: {
      accent: '#d94f4f',
      diffAdd: '#b3e6cc',
      diffDelete: '#f5b3b3',
      error: '#d94f4f',
      info: '#5bb8d9',
      ink: '#2d2640',
      neutral: '#f5f0ff',
      primary: '#a277ff',
      success: '#40bf7a',
      warning: '#d9a24a',
    },
  },
  'ayu-dark': {
    bg: '#0f1419',
    displayName: 'Ayu Dark',
    fg: '#d6dae0',
    mode: 'dark',
    name: 'opencode:ayu',
    palette: {
      accent: '#f2856f',
      diffAdd: '#59c57c',
      diffDelete: '#f58572',
      error: '#f58572',
      info: '#66c6f1',
      ink: '#d6dae0',
      neutral: '#0f1419',
      primary: '#3fb7e3',
      success: '#78d05c',
      warning: '#e4a75c',
    },
  },
  'ayu-light': {
    bg: '#fdfaf4',
    displayName: 'Ayu Light',
    fg: '#4f5964',
    mode: 'light',
    name: 'opencode:ayu',
    palette: {
      accent: '#ef7d71',
      diffAdd: '#b1d780',
      diffDelete: '#e6656a',
      error: '#e6656a',
      info: '#2f9bce',
      ink: '#4f5964',
      neutral: '#fdfaf4',
      primary: '#4aa8c8',
      success: '#5fb978',
      warning: '#ea9f41',
    },
  },
  'carbonfox-dark': {
    bg: '#393939',
    displayName: 'Carbonfox Dark',
    fg: '#f2f4f8',
    mode: 'dark',
    name: 'opencode:carbonfox',
    palette: {
      accent: '#ff8389',
      diffAdd: '#42be65',
      diffDelete: '#ff8389',
      error: '#ff8389',
      info: '#78a9ff',
      ink: '#f2f4f8',
      interactive: '#4589ff',
      neutral: '#393939',
      primary: '#33b1ff',
      success: '#42be65',
      warning: '#f1c21b',
    },
  },
  'carbonfox-light': {
    bg: '#8e8e8e',
    displayName: 'Carbonfox Light',
    fg: '#161616',
    mode: 'light',
    name: 'opencode:carbonfox',
    palette: {
      accent: '#da1e28',
      diffAdd: '#198038',
      diffDelete: '#da1e28',
      error: '#da1e28',
      info: '#0043ce',
      ink: '#161616',
      interactive: '#0f62fe',
      neutral: '#8e8e8e',
      primary: '#0072c3',
      success: '#198038',
      warning: '#f1c21b',
    },
  },
  'catppuccin-dark': {
    bg: '#1e1e2e',
    displayName: 'Catppuccin Dark',
    fg: '#cdd6f4',
    mode: 'dark',
    name: 'opencode:catppuccin',
    palette: {
      accent: '#f38ba8',
      diffAdd: '#94e2d5',
      diffDelete: '#f38ba8',
      error: '#f38ba8',
      info: '#89dceb',
      ink: '#cdd6f4',
      neutral: '#1e1e2e',
      primary: '#b4befe',
      success: '#a6d189',
      warning: '#f4b8e4',
    },
  },
  'catppuccin-light': {
    bg: '#f5e0dc',
    displayName: 'Catppuccin Light',
    fg: '#4c4f69',
    mode: 'light',
    name: 'opencode:catppuccin',
    palette: {
      accent: '#d20f39',
      diffAdd: '#a6d189',
      diffDelete: '#e78284',
      error: '#d20f39',
      info: '#04a5e5',
      ink: '#4c4f69',
      neutral: '#f5e0dc',
      primary: '#7287fd',
      success: '#40a02b',
      warning: '#df8e1d',
    },
  },
  'catppuccin-frappe-dark': {
    bg: '#303446',
    displayName: 'Catppuccin Frappe Dark',
    fg: '#c6d0f5',
    mode: 'dark',
    name: 'opencode:catppuccin-frappe',
    palette: {
      accent: '#f4b8e4',
      error: '#e78284',
      info: '#81c8be',
      ink: '#c6d0f5',
      neutral: '#303446',
      primary: '#8da4e2',
      success: '#a6d189',
      warning: '#e5c890',
    },
  },
  'catppuccin-frappe-light': {
    bg: '#303446',
    displayName: 'Catppuccin Frappe Light',
    fg: '#c6d0f5',
    mode: 'light',
    name: 'opencode:catppuccin-frappe',
    palette: {
      accent: '#f4b8e4',
      error: '#e78284',
      info: '#81c8be',
      ink: '#c6d0f5',
      neutral: '#303446',
      primary: '#8da4e2',
      success: '#a6d189',
      warning: '#e5c890',
    },
  },
  'catppuccin-macchiato-dark': {
    bg: '#24273a',
    displayName: 'Catppuccin Macchiato Dark',
    fg: '#cad3f5',
    mode: 'dark',
    name: 'opencode:catppuccin-macchiato',
    palette: {
      accent: '#f5bde6',
      error: '#ed8796',
      info: '#8bd5ca',
      ink: '#cad3f5',
      neutral: '#24273a',
      primary: '#8aadf4',
      success: '#a6da95',
      warning: '#eed49f',
    },
  },
  'catppuccin-macchiato-light': {
    bg: '#24273a',
    displayName: 'Catppuccin Macchiato Light',
    fg: '#cad3f5',
    mode: 'light',
    name: 'opencode:catppuccin-macchiato',
    palette: {
      accent: '#f5bde6',
      error: '#ed8796',
      info: '#8bd5ca',
      ink: '#cad3f5',
      neutral: '#24273a',
      primary: '#8aadf4',
      success: '#a6da95',
      warning: '#eed49f',
    },
  },
  'cobalt2-dark': {
    bg: '#193549',
    displayName: 'Cobalt2 Dark',
    fg: '#ffffff',
    mode: 'dark',
    name: 'opencode:cobalt2',
    palette: {
      accent: '#2affdf',
      diffAdd: '#b9ff9f',
      diffDelete: '#ff5fb3',
      error: '#ff0088',
      info: '#ff9d00',
      ink: '#ffffff',
      neutral: '#193549',
      primary: '#0088ff',
      success: '#9eff80',
      warning: '#ffc600',
    },
  },
  'cobalt2-light': {
    bg: '#ffffff',
    displayName: 'Cobalt2 Light',
    fg: '#193549',
    mode: 'light',
    name: 'opencode:cobalt2',
    palette: {
      accent: '#00acc1',
      error: '#e91e63',
      info: '#ff5722',
      ink: '#193549',
      neutral: '#ffffff',
      primary: '#0066cc',
      success: '#4caf50',
      warning: '#ff9800',
    },
  },
  'cursor-dark': {
    bg: '#181818',
    displayName: 'Cursor Dark',
    fg: '#e4e4e4',
    mode: 'dark',
    name: 'opencode:cursor',
    palette: {
      accent: '#88c0d0',
      diffAdd: '#70b489',
      diffDelete: '#fc6b83',
      error: '#e34671',
      info: '#81a1c1',
      ink: '#e4e4e4',
      interactive: '#82d2ce',
      neutral: '#181818',
      primary: '#88c0d0',
      success: '#3fa266',
      warning: '#f1b467',
    },
  },
  'cursor-light': {
    bg: '#fcfcfc',
    displayName: 'Cursor Light',
    fg: '#141414',
    mode: 'light',
    name: 'opencode:cursor',
    palette: {
      accent: '#6f9ba6',
      diffAdd: '#55a583',
      diffDelete: '#e75e78',
      error: '#cf2d56',
      info: '#3c7cab',
      ink: '#141414',
      interactive: '#206595',
      neutral: '#fcfcfc',
      primary: '#6f9ba6',
      success: '#1f8a65',
      warning: '#db704b',
    },
  },
  'dracula-dark': {
    bg: '#1d1e28',
    displayName: 'Dracula Dark',
    fg: '#f8f8f2',
    mode: 'dark',
    name: 'opencode:dracula',
    palette: {
      accent: '#ff79c6',
      diffAdd: '#2fb27d',
      diffDelete: '#ff6b81',
      error: '#ff5555',
      info: '#8be9fd',
      ink: '#f8f8f2',
      neutral: '#1d1e28',
      primary: '#bd93f9',
      success: '#50fa7b',
      warning: '#ffb86c',
    },
  },
  'dracula-light': {
    bg: '#f8f8f2',
    displayName: 'Dracula Light',
    fg: '#1f1f2f',
    mode: 'light',
    name: 'opencode:dracula',
    palette: {
      accent: '#d16090',
      diffAdd: '#9fe3b3',
      diffDelete: '#f8a1b8',
      error: '#d9536f',
      info: '#1d7fc5',
      ink: '#1f1f2f',
      neutral: '#f8f8f2',
      primary: '#7c6bf5',
      success: '#2fbf71',
      warning: '#f7a14d',
    },
  },
  'everforest-dark': {
    bg: '#2d353b',
    displayName: 'Everforest Dark',
    fg: '#d3c6aa',
    mode: 'dark',
    name: 'opencode:everforest',
    palette: {
      accent: '#d699b6',
      diffAdd: '#b8db87',
      diffDelete: '#e26a75',
      error: '#e67e80',
      info: '#83c092',
      ink: '#d3c6aa',
      neutral: '#2d353b',
      primary: '#a7c080',
      success: '#a7c080',
      warning: '#e69875',
    },
  },
  'everforest-light': {
    bg: '#fdf6e3',
    displayName: 'Everforest Light',
    fg: '#5c6a72',
    mode: 'light',
    name: 'opencode:everforest',
    palette: {
      accent: '#df69ba',
      diffAdd: '#4db380',
      diffDelete: '#f52a65',
      error: '#f85552',
      info: '#35a77c',
      ink: '#5c6a72',
      neutral: '#fdf6e3',
      primary: '#8da101',
      success: '#8da101',
      warning: '#f57d26',
    },
  },
  'flexoki-dark': {
    bg: '#100f0f',
    displayName: 'Flexoki Dark',
    fg: '#cecdc3',
    mode: 'dark',
    name: 'opencode:flexoki',
    palette: {
      accent: '#8b7ec8',
      error: '#d14d41',
      info: '#3aa99f',
      ink: '#cecdc3',
      interactive: '#4385be',
      neutral: '#100f0f',
      primary: '#da702c',
      success: '#879a39',
      warning: '#da702c',
    },
  },
  'flexoki-light': {
    bg: '#fffcf0',
    displayName: 'Flexoki Light',
    fg: '#100f0f',
    mode: 'light',
    name: 'opencode:flexoki',
    palette: {
      accent: '#bc5215',
      error: '#af3029',
      info: '#24837b',
      ink: '#100f0f',
      neutral: '#fffcf0',
      primary: '#205ea6',
      success: '#66800b',
      warning: '#bc5215',
    },
  },
  'github-dark': {
    bg: '#0d1117',
    displayName: 'GitHub Dark',
    fg: '#c9d1d9',
    mode: 'dark',
    name: 'opencode:github',
    palette: {
      accent: '#39c5cf',
      error: '#f85149',
      info: '#d29922',
      ink: '#c9d1d9',
      neutral: '#0d1117',
      primary: '#58a6ff',
      success: '#3fb950',
      warning: '#e3b341',
    },
  },
  'github-light': {
    bg: '#ffffff',
    displayName: 'GitHub Light',
    fg: '#24292f',
    mode: 'light',
    name: 'opencode:github',
    palette: {
      accent: '#1b7c83',
      error: '#cf222e',
      info: '#bc4c00',
      ink: '#24292f',
      neutral: '#ffffff',
      primary: '#0969da',
      success: '#1a7f37',
      warning: '#9a6700',
    },
  },
  'gruvbox-dark': {
    bg: '#282828',
    displayName: 'Gruvbox Dark',
    fg: '#ebdbb2',
    mode: 'dark',
    name: 'opencode:gruvbox',
    palette: {
      accent: '#fb4934',
      diffAdd: '#b8bb26',
      diffDelete: '#fb4934',
      error: '#fb4934',
      info: '#d3869b',
      ink: '#ebdbb2',
      neutral: '#282828',
      primary: '#83a598',
      success: '#b8bb26',
      warning: '#fabd2f',
    },
  },
  'gruvbox-light': {
    bg: '#fbf1c7',
    displayName: 'Gruvbox Light',
    fg: '#3c3836',
    mode: 'light',
    name: 'opencode:gruvbox',
    palette: {
      accent: '#9d0006',
      diffAdd: '#79740e',
      diffDelete: '#9d0006',
      error: '#9d0006',
      info: '#8f3f71',
      ink: '#3c3836',
      neutral: '#fbf1c7',
      primary: '#076678',
      success: '#79740e',
      warning: '#b57614',
    },
  },
  'kanagawa-dark': {
    bg: '#1f1f28',
    displayName: 'Kanagawa Dark',
    fg: '#dcd7ba',
    mode: 'dark',
    name: 'opencode:kanagawa',
    palette: {
      accent: '#d27e99',
      diffAdd: '#a9d977',
      diffDelete: '#f24a4a',
      error: '#e82424',
      info: '#76946a',
      ink: '#dcd7ba',
      neutral: '#1f1f28',
      primary: '#7e9cd8',
      success: '#98bb6c',
      warning: '#d7a657',
    },
  },
  'kanagawa-light': {
    bg: '#f2e9de',
    displayName: 'Kanagawa Light',
    fg: '#54433a',
    mode: 'light',
    name: 'opencode:kanagawa',
    palette: {
      accent: '#d27e99',
      diffAdd: '#89af5b',
      diffDelete: '#d61f1f',
      error: '#e82424',
      info: '#76946a',
      ink: '#54433a',
      neutral: '#f2e9de',
      primary: '#2d4f67',
      success: '#98bb6c',
      warning: '#d7a657',
    },
  },
  'lucent-orng-dark': {
    bg: '#2a1a15',
    displayName: 'Lucent Orng Dark',
    fg: '#eeeeee',
    mode: 'dark',
    name: 'opencode:lucent-orng',
    palette: {
      accent: '#fff7f1',
      diffDelete: '#e26a75',
      error: '#e06c75',
      info: '#56b6c2',
      ink: '#eeeeee',
      neutral: '#2a1a15',
      primary: '#ec5b2b',
      success: '#6ba1e6',
      warning: '#ec5b2b',
    },
  },
  'lucent-orng-light': {
    bg: '#fff5f0',
    displayName: 'Lucent Orng Light',
    fg: '#1a1a1a',
    mode: 'light',
    name: 'opencode:lucent-orng',
    palette: {
      accent: '#c94d24',
      diffDelete: '#f52a65',
      error: '#d1383d',
      info: '#318795',
      ink: '#1a1a1a',
      neutral: '#fff5f0',
      primary: '#ec5b2b',
      success: '#0062d1',
      warning: '#ec5b2b',
    },
  },
  'material-dark': {
    bg: '#263238',
    displayName: 'Material Dark',
    fg: '#eeffff',
    mode: 'dark',
    name: 'opencode:material',
    palette: {
      accent: '#89ddff',
      error: '#f07178',
      info: '#ffcb6b',
      ink: '#eeffff',
      interactive: '#89ddff',
      neutral: '#263238',
      primary: '#82aaff',
      success: '#c3e88d',
      warning: '#ffcb6b',
    },
  },
  'material-light': {
    bg: '#fafafa',
    displayName: 'Material Light',
    fg: '#263238',
    mode: 'light',
    name: 'opencode:material',
    palette: {
      accent: '#39adb5',
      error: '#e53935',
      info: '#f4511e',
      ink: '#263238',
      interactive: '#39adb5',
      neutral: '#fafafa',
      primary: '#6182b8',
      success: '#91b859',
      warning: '#ffb300',
    },
  },
  'matrix-dark': {
    bg: '#0a0e0a',
    displayName: 'Matrix Dark',
    fg: '#62ff94',
    mode: 'dark',
    name: 'opencode:matrix',
    palette: {
      accent: '#c770ff',
      diffAdd: '#77ffaf',
      diffDelete: '#ff7171',
      error: '#ff4b4b',
      info: '#30b3ff',
      ink: '#62ff94',
      interactive: '#30b3ff',
      neutral: '#0a0e0a',
      primary: '#2eff6a',
      success: '#62ff94',
      warning: '#e6ff57',
    },
  },
  'matrix-light': {
    bg: '#eef3ea',
    displayName: 'Matrix Light',
    fg: '#203022',
    mode: 'light',
    name: 'opencode:matrix',
    palette: {
      accent: '#c770ff',
      diffAdd: '#5dac7e',
      diffDelete: '#d53a3a',
      error: '#ff4b4b',
      info: '#30b3ff',
      ink: '#203022',
      interactive: '#30b3ff',
      neutral: '#eef3ea',
      primary: '#1cc24b',
      success: '#1cc24b',
      warning: '#e6ff57',
    },
  },
  'mercury-dark': {
    bg: '#171721',
    displayName: 'Mercury Dark',
    fg: '#dddde5',
    mode: 'dark',
    name: 'opencode:mercury',
    palette: {
      accent: '#8da4f5',
      error: '#fc92b4',
      info: '#77becf',
      ink: '#dddde5',
      neutral: '#171721',
      primary: '#8da4f5',
      success: '#77c599',
      warning: '#fc9b6f',
    },
  },
  'mercury-light': {
    bg: '#ffffff',
    displayName: 'Mercury Light',
    fg: '#363644',
    mode: 'light',
    name: 'opencode:mercury',
    palette: {
      accent: '#8da4f5',
      error: '#b0175f',
      info: '#007f95',
      ink: '#363644',
      interactive: '#465bd1',
      neutral: '#ffffff',
      primary: '#5266eb',
      success: '#036e43',
      warning: '#a44200',
    },
  },
  'monokai-dark': {
    bg: '#272822',
    displayName: 'Monokai Dark',
    fg: '#f8f8f2',
    mode: 'dark',
    name: 'opencode:monokai',
    palette: {
      accent: '#f92672',
      diffAdd: '#4d7f2a',
      diffDelete: '#f4477c',
      error: '#f92672',
      info: '#66d9ef',
      ink: '#f8f8f2',
      neutral: '#272822',
      primary: '#ae81ff',
      success: '#a6e22e',
      warning: '#fd971f',
    },
  },
  'monokai-light': {
    bg: '#fdf8ec',
    displayName: 'Monokai Light',
    fg: '#292318',
    mode: 'light',
    name: 'opencode:monokai',
    palette: {
      accent: '#d9487c',
      diffAdd: '#bfe7a3',
      diffDelete: '#f6a3ae',
      error: '#e54b4b',
      info: '#2d9ad7',
      ink: '#292318',
      neutral: '#fdf8ec',
      primary: '#bf7bff',
      success: '#4fb54b',
      warning: '#f1a948',
    },
  },
  'nightowl-dark': {
    bg: '#011627',
    displayName: 'Night Owl Dark',
    fg: '#d6deeb',
    mode: 'dark',
    name: 'opencode:nightowl',
    palette: {
      accent: '#f78c6c',
      diffAdd: '#c5e478',
      diffDelete: '#ef5350',
      error: '#ef5350',
      info: '#82aaff',
      ink: '#d6deeb',
      neutral: '#011627',
      primary: '#82aaff',
      success: '#c5e478',
      warning: '#ecc48d',
    },
  },
  'nightowl-light': {
    bg: '#f0f0f0',
    displayName: 'Night Owl Light',
    fg: '#403f53',
    mode: 'light',
    name: 'opencode:nightowl',
    palette: {
      accent: '#aa0982',
      diffAdd: '#2aa298',
      diffDelete: '#de3d3b',
      error: '#de3d3b',
      info: '#4876d6',
      ink: '#403f53',
      neutral: '#f0f0f0',
      primary: '#4876d6',
      success: '#2aa298',
      warning: '#c96765',
    },
  },
  'nord-dark': {
    bg: '#2e3440',
    displayName: 'Nord Dark',
    fg: '#e5e9f0',
    mode: 'dark',
    name: 'opencode:nord',
    palette: {
      accent: '#d57780',
      diffAdd: '#81a1c1',
      diffDelete: '#bf616a',
      error: '#bf616a',
      info: '#81a1c1',
      ink: '#e5e9f0',
      neutral: '#2e3440',
      primary: '#88c0d0',
      success: '#a3be8c',
      warning: '#d08770',
    },
  },
  'nord-light': {
    bg: '#eceff4',
    displayName: 'Nord Light',
    fg: '#2e3440',
    mode: 'light',
    name: 'opencode:nord',
    palette: {
      accent: '#bf616a',
      diffAdd: '#a3be8c',
      diffDelete: '#bf616a',
      error: '#bf616a',
      info: '#81a1c1',
      ink: '#2e3440',
      neutral: '#eceff4',
      primary: '#5e81ac',
      success: '#8fbcbb',
      warning: '#d08770',
    },
  },
  'oc-2-dark': {
    bg: '#1f1f1f',
    displayName: 'OC-2 Dark',
    fg: '#f1ece8',
    mode: 'dark',
    name: 'opencode:oc-2',
    palette: {
      diffAdd: '#c8ffc4',
      diffDelete: '#fc533a',
      error: '#fc533a',
      info: '#edb2f1',
      ink: '#f1ece8',
      interactive: '#034cff',
      neutral: '#1f1f1f',
      primary: '#fab283',
      success: '#12c905',
      warning: '#fcd53a',
    },
  },
  'oc-2-light': {
    bg: '#f7f7f7',
    displayName: 'OC-2 Light',
    fg: '#171311',
    mode: 'light',
    name: 'opencode:oc-2',
    palette: {
      diffAdd: '#9ff29a',
      diffDelete: '#fc533a',
      error: '#fc533a',
      info: '#a753ae',
      ink: '#171311',
      interactive: '#034cff',
      neutral: '#f7f7f7',
      primary: '#dcde8d',
      success: '#12c905',
      warning: '#ffdc17',
    },
  },
  'one-dark-dark': {
    bg: '#282c34',
    displayName: 'One Dark Dark',
    fg: '#abb2bf',
    mode: 'dark',
    name: 'opencode:one-dark',
    palette: {
      accent: '#56b6c2',
      diffAdd: '#aad482',
      diffDelete: '#e8828b',
      error: '#e06c75',
      info: '#d19a66',
      ink: '#abb2bf',
      neutral: '#282c34',
      primary: '#61afef',
      success: '#98c379',
      warning: '#e5c07b',
    },
  },
  'one-dark-light': {
    bg: '#fafafa',
    displayName: 'One Dark Light',
    fg: '#383a42',
    mode: 'light',
    name: 'opencode:one-dark',
    palette: {
      accent: '#0184bc',
      diffAdd: '#489447',
      diffDelete: '#d65145',
      error: '#e45649',
      info: '#986801',
      ink: '#383a42',
      neutral: '#fafafa',
      primary: '#4078f2',
      success: '#50a14f',
      warning: '#c18401',
    },
  },
  'onedarkpro-dark': {
    bg: '#1e222a',
    displayName: 'One Dark Pro Dark',
    fg: '#abb2bf',
    mode: 'dark',
    name: 'opencode:onedarkpro',
    palette: {
      accent: '#e06c75',
      diffAdd: '#4b815a',
      diffDelete: '#b2555f',
      error: '#e06c75',
      info: '#56b6c2',
      ink: '#abb2bf',
      neutral: '#1e222a',
      primary: '#61afef',
      success: '#98c379',
      warning: '#e5c07b',
    },
  },
  'onedarkpro-light': {
    bg: '#f5f6f8',
    displayName: 'One Dark Pro Light',
    fg: '#2b303b',
    mode: 'light',
    name: 'opencode:onedarkpro',
    palette: {
      accent: '#d85462',
      diffAdd: '#c2ebcf',
      diffDelete: '#f7c1c5',
      error: '#e06c75',
      info: '#61afef',
      ink: '#2b303b',
      neutral: '#f5f6f8',
      primary: '#528bff',
      success: '#4fa66d',
      warning: '#d19a66',
    },
  },
  'opencode-dark': {
    bg: '#0a0a0a',
    displayName: 'OpenCode Dark',
    fg: '#eeeeee',
    mode: 'dark',
    name: 'opencode:opencode',
    palette: {
      accent: '#9d7cd8',
      diffAdd: '#b8db87',
      diffDelete: '#e26a75',
      error: '#e06c75',
      info: '#56b6c2',
      ink: '#eeeeee',
      neutral: '#0a0a0a',
      primary: '#fab283',
      success: '#7fd88f',
      warning: '#f5a742',
    },
  },
  'opencode-light': {
    bg: '#ffffff',
    displayName: 'OpenCode Light',
    fg: '#1a1a1a',
    mode: 'light',
    name: 'opencode:opencode',
    palette: {
      accent: '#d68c27',
      diffAdd: '#4db380',
      diffDelete: '#f52a65',
      error: '#d1383d',
      info: '#318795',
      ink: '#1a1a1a',
      neutral: '#ffffff',
      primary: '#3b7dd8',
      success: '#3d9a57',
      warning: '#d68c27',
    },
  },
  'orng-dark': {
    bg: '#0a0a0a',
    displayName: 'Orng Dark',
    fg: '#eeeeee',
    mode: 'dark',
    name: 'opencode:orng',
    palette: {
      accent: '#fff7f1',
      diffDelete: '#e26a75',
      error: '#e06c75',
      info: '#56b6c2',
      ink: '#eeeeee',
      neutral: '#0a0a0a',
      primary: '#ec5b2b',
      success: '#6ba1e6',
      warning: '#ec5b2b',
    },
  },
  'orng-light': {
    bg: '#ffffff',
    displayName: 'Orng Light',
    fg: '#1a1a1a',
    mode: 'light',
    name: 'opencode:orng',
    palette: {
      accent: '#c94d24',
      diffDelete: '#f52a65',
      error: '#d1383d',
      info: '#318795',
      ink: '#1a1a1a',
      neutral: '#ffffff',
      primary: '#ec5b2b',
      success: '#0062d1',
      warning: '#ec5b2b',
    },
  },
  'osaka-jade-dark': {
    bg: '#111c18',
    displayName: 'Osaka Jade Dark',
    fg: '#c1c497',
    mode: 'dark',
    name: 'opencode:osaka-jade',
    palette: {
      accent: '#549e6a',
      diffAdd: '#63b07a',
      diffDelete: '#db9f9c',
      error: '#ff5345',
      info: '#2dd5b7',
      ink: '#c1c497',
      interactive: '#8cd3cb',
      neutral: '#111c18',
      primary: '#2dd5b7',
      success: '#549e6a',
      warning: '#e5c736',
    },
  },
  'osaka-jade-light': {
    bg: '#f6f5dd',
    displayName: 'Osaka Jade Light',
    fg: '#111c18',
    mode: 'light',
    name: 'opencode:osaka-jade',
    palette: {
      accent: '#3d7a52',
      error: '#c7392d',
      info: '#1faa90',
      ink: '#111c18',
      neutral: '#f6f5dd',
      primary: '#1faa90',
      success: '#3d7a52',
      warning: '#b5a020',
    },
  },
  'palenight-dark': {
    bg: '#292d3e',
    displayName: 'Palenight Dark',
    fg: '#a6accd',
    mode: 'dark',
    name: 'opencode:palenight',
    palette: {
      accent: '#89ddff',
      error: '#f07178',
      info: '#f78c6c',
      ink: '#a6accd',
      neutral: '#292d3e',
      primary: '#82aaff',
      success: '#c3e88d',
      warning: '#ffcb6b',
    },
  },
  'palenight-light': {
    bg: '#fafafa',
    displayName: 'Palenight Light',
    fg: '#292d3e',
    mode: 'light',
    name: 'opencode:palenight',
    palette: {
      accent: '#00acc1',
      error: '#e53935',
      info: '#f4511e',
      ink: '#292d3e',
      neutral: '#fafafa',
      primary: '#4976eb',
      success: '#91b859',
      warning: '#ffb300',
    },
  },
  'rosepine-dark': {
    bg: '#191724',
    displayName: 'Rose Pine Dark',
    fg: '#e0def4',
    mode: 'dark',
    name: 'opencode:rosepine',
    palette: {
      accent: '#ebbcba',
      error: '#eb6f92',
      info: '#9ccfd8',
      ink: '#e0def4',
      neutral: '#191724',
      primary: '#9ccfd8',
      success: '#31748f',
      warning: '#f6c177',
    },
  },
  'rosepine-light': {
    bg: '#faf4ed',
    displayName: 'Rose Pine Light',
    fg: '#575279',
    mode: 'light',
    name: 'opencode:rosepine',
    palette: {
      accent: '#d7827e',
      error: '#b4637a',
      info: '#56949f',
      ink: '#575279',
      neutral: '#faf4ed',
      primary: '#31748f',
      success: '#286983',
      warning: '#ea9d34',
    },
  },
  'shadesofpurple-dark': {
    bg: '#1a102b',
    displayName: 'Shades of Purple Dark',
    fg: '#f5f0ff',
    mode: 'dark',
    name: 'opencode:shadesofpurple',
    palette: {
      accent: '#ff7ac6',
      diffAdd: '#53c39f',
      diffDelete: '#d85aa0',
      error: '#ff7ac6',
      info: '#7dd4ff',
      ink: '#f5f0ff',
      neutral: '#1a102b',
      primary: '#c792ff',
      success: '#7be0b0',
      warning: '#ffd580',
    },
  },
  'shadesofpurple-light': {
    bg: '#f7ebff',
    displayName: 'Shades of Purple Light',
    fg: '#3b2c59',
    mode: 'light',
    name: 'opencode:shadesofpurple',
    palette: {
      accent: '#ff6bd5',
      diffAdd: '#c8f8da',
      diffDelete: '#ffc3ef',
      error: '#ff6bd5',
      info: '#62d4ff',
      ink: '#3b2c59',
      neutral: '#f7ebff',
      primary: '#7a5af8',
      success: '#3dd598',
      warning: '#f7c948',
    },
  },
  'solarized-dark': {
    bg: '#002b36',
    displayName: 'Solarized Dark',
    fg: '#93a1a1',
    mode: 'dark',
    name: 'opencode:solarized',
    palette: {
      accent: '#d33682',
      diffAdd: '#4c7654',
      diffDelete: '#c34b4b',
      error: '#dc322f',
      info: '#2aa198',
      ink: '#93a1a1',
      neutral: '#002b36',
      primary: '#6c71c4',
      success: '#859900',
      warning: '#b58900',
    },
  },
  'solarized-light': {
    bg: '#fdf6e3',
    displayName: 'Solarized Light',
    fg: '#586e75',
    mode: 'light',
    name: 'opencode:solarized',
    palette: {
      accent: '#d33682',
      diffAdd: '#c6dc7a',
      diffDelete: '#f2a1a1',
      error: '#dc322f',
      info: '#2aa198',
      ink: '#586e75',
      neutral: '#fdf6e3',
      primary: '#268bd2',
      success: '#859900',
      warning: '#b58900',
    },
  },
  'synthwave84-dark': {
    bg: '#262335',
    displayName: "Synthwave '84 Dark",
    fg: '#ffffff',
    mode: 'dark',
    name: 'opencode:synthwave84',
    palette: {
      accent: '#b084eb',
      diffAdd: '#97f1d8',
      diffDelete: '#ff5e5b',
      error: '#fe4450',
      info: '#ff8b39',
      ink: '#ffffff',
      neutral: '#262335',
      primary: '#36f9f6',
      success: '#72f1b8',
      warning: '#fede5d',
    },
  },
  'synthwave84-light': {
    bg: '#fafafa',
    displayName: "Synthwave '84 Light",
    fg: '#262335',
    mode: 'light',
    name: 'opencode:synthwave84',
    palette: {
      accent: '#9c27b0',
      error: '#f44336',
      info: '#ff5722',
      ink: '#262335',
      neutral: '#fafafa',
      primary: '#00bcd4',
      success: '#4caf50',
      warning: '#ff9800',
    },
  },
  'tokyonight-dark': {
    bg: '#1a1b26',
    displayName: 'Tokyonight Dark',
    fg: '#c0caf5',
    mode: 'dark',
    name: 'opencode:tokyonight',
    palette: {
      accent: '#ff9e64',
      diffAdd: '#41a6b5',
      diffDelete: '#c34043',
      error: '#f7768e',
      info: '#7dcfff',
      ink: '#c0caf5',
      neutral: '#1a1b26',
      primary: '#7aa2f7',
      success: '#9ece6a',
      warning: '#e0af68',
    },
  },
  'tokyonight-light': {
    bg: '#e1e2e7',
    displayName: 'Tokyonight Light',
    fg: '#273153',
    mode: 'light',
    name: 'opencode:tokyonight',
    palette: {
      accent: '#b15c00',
      diffAdd: '#4f8f7b',
      diffDelete: '#d05f7c',
      error: '#c94060',
      info: '#007197',
      ink: '#273153',
      neutral: '#e1e2e7',
      primary: '#2e7de9',
      success: '#587539',
      warning: '#8c6c3e',
    },
  },
  'vercel-dark': {
    bg: '#000000',
    displayName: 'Vercel Dark',
    fg: '#ededed',
    mode: 'dark',
    name: 'opencode:vercel',
    palette: {
      accent: '#8e4ec6',
      diffAdd: '#63c46d',
      diffDelete: '#ff6166',
      error: '#e5484d',
      info: '#52a8ff',
      ink: '#ededed',
      interactive: '#52a8ff',
      neutral: '#000000',
      primary: '#0070f3',
      success: '#46a758',
      warning: '#ffb224',
    },
  },
  'vercel-light': {
    bg: '#ffffff',
    displayName: 'Vercel Light',
    fg: '#171717',
    mode: 'light',
    name: 'opencode:vercel',
    palette: {
      accent: '#8e4ec6',
      diffAdd: '#46a758',
      diffDelete: '#e5484d',
      error: '#dc3545',
      info: '#0070f3',
      ink: '#171717',
      neutral: '#ffffff',
      primary: '#0070f3',
      success: '#388e3c',
      warning: '#ff9500',
    },
  },
  'vesper-dark': {
    bg: '#101010',
    displayName: 'Vesper Dark',
    fg: '#ffffff',
    mode: 'dark',
    name: 'opencode:vesper',
    palette: {
      accent: '#ff8080',
      diffAdd: '#99ffe4',
      diffDelete: '#ff8080',
      error: '#ff8080',
      info: '#ffc799',
      ink: '#ffffff',
      neutral: '#101010',
      primary: '#ffc799',
      success: '#99ffe4',
      warning: '#ffc799',
    },
  },
  'vesper-light': {
    bg: '#f0f0f0',
    displayName: 'Vesper Light',
    fg: '#101010',
    mode: 'light',
    name: 'opencode:vesper',
    palette: {
      accent: '#b30000',
      diffAdd: '#99ffe4',
      diffDelete: '#ff8080',
      error: '#ff8080',
      info: '#ffc799',
      ink: '#101010',
      neutral: '#f0f0f0',
      primary: '#ffc799',
      success: '#99ffe4',
      warning: '#ffc799',
    },
  },
  'zenburn-dark': {
    bg: '#3f3f3f',
    displayName: 'Zenburn Dark',
    fg: '#dcdccc',
    mode: 'dark',
    name: 'opencode:zenburn',
    palette: {
      accent: '#93e0e3',
      diffAdd: '#8fb28f',
      diffDelete: '#dca3a3',
      error: '#cc9393',
      info: '#dfaf8f',
      ink: '#dcdccc',
      neutral: '#3f3f3f',
      primary: '#8cd0d3',
      success: '#7f9f7f',
      warning: '#f0dfaf',
    },
  },
  'zenburn-light': {
    bg: '#ffffef',
    displayName: 'Zenburn Light',
    fg: '#3f3f3f',
    mode: 'light',
    name: 'opencode:zenburn',
    palette: {
      accent: '#5f8f8f',
      error: '#8f5f5f',
      info: '#8f7f5f',
      ink: '#3f3f3f',
      neutral: '#ffffef',
      primary: '#5f7f8f',
      success: '#5f8f5f',
      warning: '#8f8f5f',
    },
  },
}

export const OPENCODE_THEME_IDS: string[] = [
  'amoled-dark',
  'amoled-light',
  'aura-dark',
  'aura-light',
  'ayu-dark',
  'ayu-light',
  'carbonfox-dark',
  'carbonfox-light',
  'catppuccin-dark',
  'catppuccin-light',
  'catppuccin-frappe-dark',
  'catppuccin-frappe-light',
  'catppuccin-macchiato-dark',
  'catppuccin-macchiato-light',
  'cobalt2-dark',
  'cobalt2-light',
  'cursor-dark',
  'cursor-light',
  'dracula-dark',
  'dracula-light',
  'everforest-dark',
  'everforest-light',
  'flexoki-dark',
  'flexoki-light',
  'github-dark',
  'github-light',
  'gruvbox-dark',
  'gruvbox-light',
  'kanagawa-dark',
  'kanagawa-light',
  'lucent-orng-dark',
  'lucent-orng-light',
  'material-dark',
  'material-light',
  'matrix-dark',
  'matrix-light',
  'mercury-dark',
  'mercury-light',
  'monokai-dark',
  'monokai-light',
  'nightowl-dark',
  'nightowl-light',
  'nord-dark',
  'nord-light',
  'oc-2-dark',
  'oc-2-light',
  'one-dark-dark',
  'one-dark-light',
  'onedarkpro-dark',
  'onedarkpro-light',
  'opencode-dark',
  'opencode-light',
  'orng-dark',
  'orng-light',
  'osaka-jade-dark',
  'osaka-jade-light',
  'palenight-dark',
  'palenight-light',
  'rosepine-dark',
  'rosepine-light',
  'shadesofpurple-dark',
  'shadesofpurple-light',
  'solarized-dark',
  'solarized-light',
  'synthwave84-dark',
  'synthwave84-light',
  'tokyonight-dark',
  'tokyonight-light',
  'vercel-dark',
  'vercel-light',
  'vesper-dark',
  'vesper-light',
  'zenburn-dark',
  'zenburn-light',
]
