// AUTO-GENERATED — run `bun scripts/import-opencode-themes.ts` to regenerate.
// Source: https://github.com/sst/opencode/tree/dev/packages/ui/src/theme/themes
// License: MIT (sst/opencode)
/* eslint-disable */

import type { AimuxTheme } from '../types'

export const OPENCODE_THEMES: Record<string, AimuxTheme> = {
  'amoled-dark': {
    bg: '#000000',
    displayName: 'AMOLED Dark',
    fg: '#ffffff',
    mode: 'dark',
    name: 'opencode:amoled',
    overrides: {
      'syntax-comment': '#555555',
      'syntax-constant': '#b388ff',
      'syntax-keyword': '#ff00ff',
      'syntax-primitive': '#18ffff',
      'syntax-property': '#ffea00',
      'syntax-string': '#00ff88',
    },
    palette: {
      accent: '#ff4081',
      diffAdd: '#00ff88',
      diffDelete: '#ff1744',
      error: '#ff1744',
      info: '#18ffff',
      ink: '#ffffff',
      neutral: '#000000',
      primary: '#b388ff',
      success: '#00ff88',
      warning: '#ffea00',
    },
  },
  'amoled-light': {
    bg: '#f0f0f0',
    displayName: 'AMOLED Light',
    fg: '#0a0a0a',
    mode: 'light',
    name: 'opencode:amoled',
    overrides: {
      'syntax-comment': '#757575',
      'syntax-constant': '#6200ff',
      'syntax-keyword': '#d500f9',
      'syntax-primitive': '#00b0ff',
      'syntax-property': '#ff9100',
      'syntax-string': '#00e676',
    },
    palette: {
      accent: '#ff0080',
      diffAdd: '#00e676',
      diffDelete: '#ff1744',
      error: '#ff1744',
      info: '#00b0ff',
      ink: '#0a0a0a',
      neutral: '#f0f0f0',
      primary: '#6200ff',
      success: '#00e676',
      warning: '#ffab00',
    },
  },
  'aura-dark': {
    bg: '#15141b',
    displayName: 'Aura Dark',
    fg: '#edecee',
    mode: 'dark',
    name: 'opencode:aura',
    overrides: {
      'syntax-comment': '#6d6a7e',
      'syntax-constant': '#ff6767',
      'syntax-keyword': '#a277ff',
      'syntax-primitive': '#82e2ff',
      'syntax-property': '#ffca85',
      'syntax-string': '#61ffca',
      'syntax-type': '#61ffca',
    },
    palette: {
      accent: '#ff6767',
      diffAdd: '#61ffca',
      diffDelete: '#ff6767',
      error: '#ff6767',
      info: '#82e2ff',
      ink: '#edecee',
      neutral: '#15141b',
      primary: '#a277ff',
      success: '#61ffca',
      warning: '#ffca85',
    },
  },
  'aura-light': {
    bg: '#f5f0ff',
    displayName: 'Aura Light',
    fg: '#2d2640',
    mode: 'light',
    name: 'opencode:aura',
    overrides: {
      'syntax-comment': '#8d88a3',
      'syntax-constant': '#d94f4f',
      'syntax-keyword': '#7b5ae0',
      'syntax-primitive': '#2f78b8',
      'syntax-property': '#a96a22',
      'syntax-string': '#2b8a57',
      'syntax-type': '#2b8a57',
    },
    palette: {
      accent: '#d94f4f',
      diffAdd: '#b3e6cc',
      diffDelete: '#f5b3b3',
      error: '#d94f4f',
      info: '#5bb8d9',
      ink: '#2d2640',
      neutral: '#f5f0ff',
      primary: '#a277ff',
      success: '#40bf7a',
      warning: '#d9a24a',
    },
  },
  'ayu-dark': {
    bg: '#0f1419',
    displayName: 'Ayu Dark',
    fg: '#d6dae0',
    mode: 'dark',
    name: 'opencode:ayu',
    overrides: {
      'syntax-comment': '#5a6673',
      'syntax-constant': '#d2a6ff',
      'syntax-keyword': '#ff8f40',
      'syntax-primitive': '#ffb454',
      'syntax-property': '#39bae6',
      'syntax-string': '#aad94c',
      'syntax-type': '#59c2ff',
    },
    palette: {
      accent: '#f2856f',
      diffAdd: '#59c57c',
      diffDelete: '#f58572',
      error: '#f58572',
      info: '#66c6f1',
      ink: '#d6dae0',
      neutral: '#0f1419',
      primary: '#3fb7e3',
      success: '#78d05c',
      warning: '#e4a75c',
    },
  },
  'ayu-light': {
    bg: '#fdfaf4',
    displayName: 'Ayu Light',
    fg: '#4f5964',
    mode: 'light',
    name: 'opencode:ayu',
    overrides: {
      'syntax-comment': '#6e7681',
      'syntax-constant': '#a37acc',
      'syntax-keyword': '#c76a1a',
      'syntax-primitive': '#b87500',
      'syntax-property': '#2f86b7',
      'syntax-string': '#6f8f00',
      'syntax-type': '#227fc0',
    },
    palette: {
      accent: '#ef7d71',
      diffAdd: '#b1d780',
      diffDelete: '#e6656a',
      error: '#e6656a',
      info: '#2f9bce',
      ink: '#4f5964',
      neutral: '#fdfaf4',
      primary: '#4aa8c8',
      success: '#5fb978',
      warning: '#ea9f41',
    },
  },
  'carbonfox-dark': {
    bg: '#393939',
    displayName: 'Carbonfox Dark',
    fg: '#f2f4f8',
    mode: 'dark',
    name: 'opencode:carbonfox',
    overrides: {
      'syntax-comment': '#6f6f6f',
      'syntax-constant': '#ff8389',
      'syntax-keyword': '#be95ff',
      'syntax-primitive': '#33b1ff',
      'syntax-property': '#78a9ff',
      'syntax-string': '#42be65',
      'syntax-type': '#f1c21b',
    },
    palette: {
      accent: '#ff8389',
      diffAdd: '#42be65',
      diffDelete: '#ff8389',
      error: '#ff8389',
      info: '#78a9ff',
      ink: '#f2f4f8',
      interactive: '#4589ff',
      neutral: '#393939',
      primary: '#33b1ff',
      success: '#42be65',
      warning: '#f1c21b',
    },
  },
  'carbonfox-light': {
    bg: '#8e8e8e',
    displayName: 'Carbonfox Light',
    fg: '#161616',
    mode: 'light',
    name: 'opencode:carbonfox',
    overrides: {
      'syntax-comment': '#6f6f6f',
      'syntax-constant': '#da1e28',
      'syntax-keyword': '#8a3ffc',
      'syntax-primitive': '#0f62fe',
      'syntax-property': '#0043ce',
      'syntax-string': '#198038',
      'syntax-type': '#8a5f00',
    },
    palette: {
      accent: '#da1e28',
      diffAdd: '#198038',
      diffDelete: '#da1e28',
      error: '#da1e28',
      info: '#0043ce',
      ink: '#161616',
      interactive: '#0f62fe',
      neutral: '#8e8e8e',
      primary: '#0072c3',
      success: '#198038',
      warning: '#f1c21b',
    },
  },
  'catppuccin-dark': {
    bg: '#1e1e2e',
    displayName: 'Catppuccin Dark',
    fg: '#cdd6f4',
    mode: 'dark',
    name: 'opencode:catppuccin',
    overrides: {
      'syntax-comment': '#6c7086',
      'syntax-constant': '#fab387',
      'syntax-keyword': '#cba6f7',
      'syntax-primitive': '#89b4fa',
    },
    palette: {
      accent: '#f38ba8',
      diffAdd: '#94e2d5',
      diffDelete: '#f38ba8',
      error: '#f38ba8',
      info: '#89dceb',
      ink: '#cdd6f4',
      neutral: '#1e1e2e',
      primary: '#b4befe',
      success: '#a6d189',
      warning: '#f4b8e4',
    },
  },
  'catppuccin-light': {
    bg: '#f5e0dc',
    displayName: 'Catppuccin Light',
    fg: '#4c4f69',
    mode: 'light',
    name: 'opencode:catppuccin',
    overrides: {
      'syntax-comment': '#6c7086',
      'syntax-constant': '#ca6702',
      'syntax-keyword': '#8839ef',
      'syntax-primitive': '#1e66f5',
    },
    palette: {
      accent: '#d20f39',
      diffAdd: '#a6d189',
      diffDelete: '#e78284',
      error: '#d20f39',
      info: '#04a5e5',
      ink: '#4c4f69',
      neutral: '#f5e0dc',
      primary: '#7287fd',
      success: '#40a02b',
      warning: '#df8e1d',
    },
  },
  'catppuccin-frappe-dark': {
    bg: '#303446',
    displayName: 'Catppuccin Frappe Dark',
    fg: '#c6d0f5',
    mode: 'dark',
    name: 'opencode:catppuccin-frappe',
    overrides: {
      'markdown-block-quote': '#e5c890',
      'markdown-code': '#a6d189',
      'markdown-code-block': '#c6d0f5',
      'markdown-emph': '#e5c890',
      'markdown-heading': '#ca9ee6',
      'markdown-horizontal-rule': '#a5adce',
      'markdown-image': '#8da4e2',
      'markdown-image-text': '#99d1db',
      'markdown-link': '#8da4e2',
      'markdown-link-text': '#99d1db',
      'markdown-list-enumeration': '#99d1db',
      'markdown-list-item': '#8da4e2',
      'markdown-strong': '#ef9f76',
      'markdown-text': '#c6d0f5',
      'syntax-comment': '#949cb8',
      'syntax-constant': '#ef9f76',
      'syntax-keyword': '#ca9ee6',
      'syntax-object': '#e78284',
      'syntax-operator': '#99d1db',
      'syntax-primitive': '#8da4e2',
      'syntax-property': '#99d1db',
      'syntax-punctuation': '#c6d0f5',
      'syntax-string': '#a6d189',
      'syntax-type': '#e5c890',
      'syntax-variable': '#e78284',
      'text-weak': '#b5bfe2',
    },
    palette: {
      accent: '#f4b8e4',
      error: '#e78284',
      info: '#81c8be',
      ink: '#c6d0f5',
      neutral: '#303446',
      primary: '#8da4e2',
      success: '#a6d189',
      warning: '#e5c890',
    },
  },
  'catppuccin-frappe-light': {
    bg: '#303446',
    displayName: 'Catppuccin Frappe Light',
    fg: '#c6d0f5',
    mode: 'light',
    name: 'opencode:catppuccin-frappe',
    overrides: {
      'markdown-block-quote': '#e5c890',
      'markdown-code': '#a6d189',
      'markdown-code-block': '#c6d0f5',
      'markdown-emph': '#e5c890',
      'markdown-heading': '#ca9ee6',
      'markdown-horizontal-rule': '#a5adce',
      'markdown-image': '#8da4e2',
      'markdown-image-text': '#99d1db',
      'markdown-link': '#8da4e2',
      'markdown-link-text': '#99d1db',
      'markdown-list-enumeration': '#99d1db',
      'markdown-list-item': '#8da4e2',
      'markdown-strong': '#ef9f76',
      'markdown-text': '#c6d0f5',
      'syntax-comment': '#949cb8',
      'syntax-constant': '#ef9f76',
      'syntax-keyword': '#ca9ee6',
      'syntax-object': '#e78284',
      'syntax-operator': '#99d1db',
      'syntax-primitive': '#8da4e2',
      'syntax-property': '#99d1db',
      'syntax-punctuation': '#c6d0f5',
      'syntax-string': '#a6d189',
      'syntax-type': '#e5c890',
      'syntax-variable': '#e78284',
      'text-weak': '#b5bfe2',
    },
    palette: {
      accent: '#f4b8e4',
      error: '#e78284',
      info: '#81c8be',
      ink: '#c6d0f5',
      neutral: '#303446',
      primary: '#8da4e2',
      success: '#a6d189',
      warning: '#e5c890',
    },
  },
  'catppuccin-macchiato-dark': {
    bg: '#24273a',
    displayName: 'Catppuccin Macchiato Dark',
    fg: '#cad3f5',
    mode: 'dark',
    name: 'opencode:catppuccin-macchiato',
    overrides: {
      'markdown-block-quote': '#eed49f',
      'markdown-code': '#a6da95',
      'markdown-code-block': '#cad3f5',
      'markdown-emph': '#eed49f',
      'markdown-heading': '#c6a0f6',
      'markdown-horizontal-rule': '#a5adcb',
      'markdown-image': '#8aadf4',
      'markdown-image-text': '#91d7e3',
      'markdown-link': '#8aadf4',
      'markdown-link-text': '#91d7e3',
      'markdown-list-enumeration': '#91d7e3',
      'markdown-list-item': '#8aadf4',
      'markdown-strong': '#f5a97f',
      'markdown-text': '#cad3f5',
      'syntax-comment': '#939ab7',
      'syntax-constant': '#f5a97f',
      'syntax-keyword': '#c6a0f6',
      'syntax-object': '#ed8796',
      'syntax-operator': '#91d7e3',
      'syntax-primitive': '#8aadf4',
      'syntax-property': '#91d7e3',
      'syntax-punctuation': '#cad3f5',
      'syntax-string': '#a6da95',
      'syntax-type': '#eed49f',
      'syntax-variable': '#ed8796',
      'text-weak': '#b8c0e0',
    },
    palette: {
      accent: '#f5bde6',
      error: '#ed8796',
      info: '#8bd5ca',
      ink: '#cad3f5',
      neutral: '#24273a',
      primary: '#8aadf4',
      success: '#a6da95',
      warning: '#eed49f',
    },
  },
  'catppuccin-macchiato-light': {
    bg: '#24273a',
    displayName: 'Catppuccin Macchiato Light',
    fg: '#cad3f5',
    mode: 'light',
    name: 'opencode:catppuccin-macchiato',
    overrides: {
      'markdown-block-quote': '#eed49f',
      'markdown-code': '#a6da95',
      'markdown-code-block': '#cad3f5',
      'markdown-emph': '#eed49f',
      'markdown-heading': '#c6a0f6',
      'markdown-horizontal-rule': '#a5adcb',
      'markdown-image': '#8aadf4',
      'markdown-image-text': '#91d7e3',
      'markdown-link': '#8aadf4',
      'markdown-link-text': '#91d7e3',
      'markdown-list-enumeration': '#91d7e3',
      'markdown-list-item': '#8aadf4',
      'markdown-strong': '#f5a97f',
      'markdown-text': '#cad3f5',
      'syntax-comment': '#939ab7',
      'syntax-constant': '#f5a97f',
      'syntax-keyword': '#c6a0f6',
      'syntax-object': '#ed8796',
      'syntax-operator': '#91d7e3',
      'syntax-primitive': '#8aadf4',
      'syntax-property': '#91d7e3',
      'syntax-punctuation': '#cad3f5',
      'syntax-string': '#a6da95',
      'syntax-type': '#eed49f',
      'syntax-variable': '#ed8796',
      'text-weak': '#b8c0e0',
    },
    palette: {
      accent: '#f5bde6',
      error: '#ed8796',
      info: '#8bd5ca',
      ink: '#cad3f5',
      neutral: '#24273a',
      primary: '#8aadf4',
      success: '#a6da95',
      warning: '#eed49f',
    },
  },
  'cobalt2-dark': {
    bg: '#193549',
    displayName: 'Cobalt2 Dark',
    fg: '#ffffff',
    mode: 'dark',
    name: 'opencode:cobalt2',
    overrides: {
      'markdown-block-quote': '#adb7c9',
      'markdown-code': '#9eff80',
      'markdown-code-block': '#ffffff',
      'markdown-emph': '#ff9d00',
      'markdown-heading': '#ffc600',
      'markdown-horizontal-rule': '#2d5a7b',
      'markdown-image': '#0088ff',
      'markdown-image-text': '#2affdf',
      'markdown-link': '#0088ff',
      'markdown-link-text': '#2affdf',
      'markdown-list-enumeration': '#2affdf',
      'markdown-list-item': '#0088ff',
      'markdown-strong': '#ff628c',
      'markdown-text': '#ffffff',
      'syntax-comment': '#0088ff',
      'syntax-constant': '#ff628c',
      'syntax-keyword': '#ff9d00',
      'syntax-object': '#ffffff',
      'syntax-operator': '#ff9d00',
      'syntax-primitive': '#ffc600',
      'syntax-property': '#2affdf',
      'syntax-punctuation': '#ffffff',
      'syntax-string': '#9eff80',
      'syntax-type': '#2affdf',
      'syntax-variable': '#ffffff',
      'text-weak': '#adb7c9',
    },
    palette: {
      accent: '#2affdf',
      diffAdd: '#b9ff9f',
      diffDelete: '#ff5fb3',
      error: '#ff0088',
      info: '#ff9d00',
      ink: '#ffffff',
      neutral: '#193549',
      primary: '#0088ff',
      success: '#9eff80',
      warning: '#ffc600',
    },
  },
  'cobalt2-light': {
    bg: '#ffffff',
    displayName: 'Cobalt2 Light',
    fg: '#193549',
    mode: 'light',
    name: 'opencode:cobalt2',
    overrides: {
      'markdown-block-quote': '#5c6b7d',
      'markdown-code': '#4caf50',
      'markdown-code-block': '#193549',
      'markdown-emph': '#ff5722',
      'markdown-heading': '#ff9800',
      'markdown-horizontal-rule': '#d3dae3',
      'markdown-image': '#0066cc',
      'markdown-image-text': '#00acc1',
      'markdown-link': '#0066cc',
      'markdown-link-text': '#00acc1',
      'markdown-list-enumeration': '#00acc1',
      'markdown-list-item': '#0066cc',
      'markdown-strong': '#e91e63',
      'markdown-text': '#193549',
      'syntax-comment': '#5c6b7d',
      'syntax-constant': '#e91e63',
      'syntax-keyword': '#ff5722',
      'syntax-object': '#193549',
      'syntax-operator': '#ff5722',
      'syntax-primitive': '#ff9800',
      'syntax-property': '#00acc1',
      'syntax-punctuation': '#193549',
      'syntax-string': '#4caf50',
      'syntax-type': '#00acc1',
      'syntax-variable': '#193549',
      'text-weak': '#5c6b7d',
    },
    palette: {
      accent: '#00acc1',
      error: '#e91e63',
      info: '#ff5722',
      ink: '#193549',
      neutral: '#ffffff',
      primary: '#0066cc',
      success: '#4caf50',
      warning: '#ff9800',
    },
  },
  'cursor-dark': {
    bg: '#181818',
    displayName: 'Cursor Dark',
    fg: '#e4e4e4',
    mode: 'dark',
    name: 'opencode:cursor',
    overrides: {
      'markdown-block-quote': '#e4e4e4',
      'markdown-code': '#e394dc',
      'markdown-code-block': '#e4e4e4',
      'markdown-emph': '#82d2ce',
      'markdown-heading': '#aaa0fa',
      'markdown-horizontal-rule': '#e4e4e4',
      'markdown-image': '#88c0d0',
      'markdown-image-text': '#81a1c1',
      'markdown-link': '#82d2ce',
      'markdown-link-text': '#81a1c1',
      'markdown-list-enumeration': '#88c0d0',
      'markdown-list-item': '#e4e4e4',
      'markdown-strong': '#f8c762',
      'markdown-text': '#e4e4e4',
      'syntax-comment': '#e4e4e4',
      'syntax-constant': '#f8c762',
      'syntax-keyword': '#82d2ce',
      'syntax-object': '#e4e4e4',
      'syntax-operator': '#e4e4e4',
      'syntax-primitive': '#efb080',
      'syntax-property': '#81a1c1',
      'syntax-punctuation': '#e4e4e4',
      'syntax-string': '#e394dc',
      'syntax-type': '#efb080',
      'syntax-variable': '#e4e4e4',
      'text-weak': '#e4e4e4',
    },
    palette: {
      accent: '#88c0d0',
      diffAdd: '#70b489',
      diffDelete: '#fc6b83',
      error: '#e34671',
      info: '#81a1c1',
      ink: '#e4e4e4',
      interactive: '#82d2ce',
      neutral: '#181818',
      primary: '#88c0d0',
      success: '#3fa266',
      warning: '#f1b467',
    },
  },
  'cursor-light': {
    bg: '#fcfcfc',
    displayName: 'Cursor Light',
    fg: '#141414',
    mode: 'light',
    name: 'opencode:cursor',
    overrides: {
      'markdown-block-quote': '#141414',
      'markdown-code': '#1f8a65',
      'markdown-code-block': '#141414',
      'markdown-emph': '#141414',
      'markdown-heading': '#206595',
      'markdown-horizontal-rule': '#141414',
      'markdown-image': '#206595',
      'markdown-image-text': '#141414',
      'markdown-link': '#206595',
      'markdown-link-text': '#141414',
      'markdown-list-enumeration': '#141414',
      'markdown-list-item': '#141414',
      'markdown-strong': '#141414',
      'markdown-text': '#141414',
      'syntax-comment': '#141414',
      'syntax-constant': '#b8448b',
      'syntax-keyword': '#b3003f',
      'syntax-object': '#141414',
      'syntax-operator': '#141414',
      'syntax-primitive': '#db704b',
      'syntax-property': '#141414',
      'syntax-punctuation': '#141414',
      'syntax-string': '#9e94d5',
      'syntax-type': '#206595',
      'syntax-variable': '#141414',
      'text-weak': '#141414',
    },
    palette: {
      accent: '#6f9ba6',
      diffAdd: '#55a583',
      diffDelete: '#e75e78',
      error: '#cf2d56',
      info: '#3c7cab',
      ink: '#141414',
      interactive: '#206595',
      neutral: '#fcfcfc',
      primary: '#6f9ba6',
      success: '#1f8a65',
      warning: '#db704b',
    },
  },
  'dracula-dark': {
    bg: '#1d1e28',
    displayName: 'Dracula Dark',
    fg: '#f8f8f2',
    mode: 'dark',
    name: 'opencode:dracula',
    overrides: {
      'syntax-comment': '#6272a4',
      'syntax-constant': '#bd93f9',
      'syntax-keyword': '#ff79c6',
      'syntax-primitive': '#50fa7b',
      'syntax-property': '#8be9fd',
      'syntax-string': '#f1fa8c',
    },
    palette: {
      accent: '#ff79c6',
      diffAdd: '#2fb27d',
      diffDelete: '#ff6b81',
      error: '#ff5555',
      info: '#8be9fd',
      ink: '#f8f8f2',
      neutral: '#1d1e28',
      primary: '#bd93f9',
      success: '#50fa7b',
      warning: '#ffb86c',
    },
  },
  'dracula-light': {
    bg: '#f8f8f2',
    displayName: 'Dracula Light',
    fg: '#1f1f2f',
    mode: 'light',
    name: 'opencode:dracula',
    overrides: {
      'syntax-comment': '#7d7f97',
      'syntax-constant': '#7c6bf5',
      'syntax-keyword': '#d16090',
      'syntax-primitive': '#2f8f57',
      'syntax-property': '#1d7fc5',
      'syntax-string': '#596600',
    },
    palette: {
      accent: '#d16090',
      diffAdd: '#9fe3b3',
      diffDelete: '#f8a1b8',
      error: '#d9536f',
      info: '#1d7fc5',
      ink: '#1f1f2f',
      neutral: '#f8f8f2',
      primary: '#7c6bf5',
      success: '#2fbf71',
      warning: '#f7a14d',
    },
  },
  'everforest-dark': {
    bg: '#2d353b',
    displayName: 'Everforest Dark',
    fg: '#d3c6aa',
    mode: 'dark',
    name: 'opencode:everforest',
    overrides: {
      'markdown-block-quote': '#dbbc7f',
      'markdown-code': '#a7c080',
      'markdown-code-block': '#d3c6aa',
      'markdown-emph': '#dbbc7f',
      'markdown-heading': '#d699b6',
      'markdown-horizontal-rule': '#7a8478',
      'markdown-image': '#a7c080',
      'markdown-image-text': '#83c092',
      'markdown-link': '#a7c080',
      'markdown-link-text': '#83c092',
      'markdown-list-enumeration': '#83c092',
      'markdown-list-item': '#a7c080',
      'markdown-strong': '#e69875',
      'markdown-text': '#d3c6aa',
      'syntax-comment': '#7a8478',
      'syntax-constant': '#e69875',
      'syntax-keyword': '#d699b6',
      'syntax-object': '#e67e80',
      'syntax-operator': '#83c092',
      'syntax-primitive': '#a7c080',
      'syntax-property': '#83c092',
      'syntax-punctuation': '#d3c6aa',
      'syntax-string': '#a7c080',
      'syntax-type': '#dbbc7f',
      'syntax-variable': '#e67e80',
      'text-weak': '#7a8478',
    },
    palette: {
      accent: '#d699b6',
      diffAdd: '#b8db87',
      diffDelete: '#e26a75',
      error: '#e67e80',
      info: '#83c092',
      ink: '#d3c6aa',
      neutral: '#2d353b',
      primary: '#a7c080',
      success: '#a7c080',
      warning: '#e69875',
    },
  },
  'everforest-light': {
    bg: '#fdf6e3',
    displayName: 'Everforest Light',
    fg: '#5c6a72',
    mode: 'light',
    name: 'opencode:everforest',
    overrides: {
      'markdown-block-quote': '#dfa000',
      'markdown-code': '#8da101',
      'markdown-code-block': '#5c6a72',
      'markdown-emph': '#dfa000',
      'markdown-heading': '#df69ba',
      'markdown-horizontal-rule': '#a6b0a0',
      'markdown-image': '#8da101',
      'markdown-image-text': '#35a77c',
      'markdown-link': '#8da101',
      'markdown-link-text': '#35a77c',
      'markdown-list-enumeration': '#35a77c',
      'markdown-list-item': '#8da101',
      'markdown-strong': '#f57d26',
      'markdown-text': '#5c6a72',
      'syntax-comment': '#a6b0a0',
      'syntax-constant': '#f57d26',
      'syntax-keyword': '#df69ba',
      'syntax-object': '#f85552',
      'syntax-operator': '#35a77c',
      'syntax-primitive': '#8da101',
      'syntax-property': '#35a77c',
      'syntax-punctuation': '#5c6a72',
      'syntax-string': '#8da101',
      'syntax-type': '#dfa000',
      'syntax-variable': '#f85552',
      'text-weak': '#a6b0a0',
    },
    palette: {
      accent: '#df69ba',
      diffAdd: '#4db380',
      diffDelete: '#f52a65',
      error: '#f85552',
      info: '#35a77c',
      ink: '#5c6a72',
      neutral: '#fdf6e3',
      primary: '#8da101',
      success: '#8da101',
      warning: '#f57d26',
    },
  },
  'flexoki-dark': {
    bg: '#100f0f',
    displayName: 'Flexoki Dark',
    fg: '#cecdc3',
    mode: 'dark',
    name: 'opencode:flexoki',
    overrides: {
      'markdown-block-quote': '#d0a215',
      'markdown-code': '#3aa99f',
      'markdown-code-block': '#cecdc3',
      'markdown-emph': '#d0a215',
      'markdown-heading': '#8b7ec8',
      'markdown-horizontal-rule': '#6f6e69',
      'markdown-image': '#ce5d97',
      'markdown-image-text': '#3aa99f',
      'markdown-link': '#4385be',
      'markdown-link-text': '#3aa99f',
      'markdown-list-enumeration': '#3aa99f',
      'markdown-list-item': '#da702c',
      'markdown-strong': '#da702c',
      'markdown-text': '#cecdc3',
      'syntax-comment': '#6f6e69',
      'syntax-constant': '#8b7ec8',
      'syntax-keyword': '#879a39',
      'syntax-object': '#4385be',
      'syntax-operator': '#b7b5ac',
      'syntax-primitive': '#da702c',
      'syntax-property': '#3aa99f',
      'syntax-punctuation': '#b7b5ac',
      'syntax-string': '#3aa99f',
      'syntax-type': '#d0a215',
      'syntax-variable': '#4385be',
      'text-weak': '#6f6e69',
    },
    palette: {
      accent: '#8b7ec8',
      error: '#d14d41',
      info: '#3aa99f',
      ink: '#cecdc3',
      interactive: '#4385be',
      neutral: '#100f0f',
      primary: '#da702c',
      success: '#879a39',
      warning: '#da702c',
    },
  },
  'flexoki-light': {
    bg: '#fffcf0',
    displayName: 'Flexoki Light',
    fg: '#100f0f',
    mode: 'light',
    name: 'opencode:flexoki',
    overrides: {
      'markdown-block-quote': '#ad8301',
      'markdown-code': '#24837b',
      'markdown-code-block': '#100f0f',
      'markdown-emph': '#ad8301',
      'markdown-heading': '#5e409d',
      'markdown-horizontal-rule': '#6f6e69',
      'markdown-image': '#a02f6f',
      'markdown-image-text': '#24837b',
      'markdown-link': '#205ea6',
      'markdown-link-text': '#24837b',
      'markdown-list-enumeration': '#24837b',
      'markdown-list-item': '#bc5215',
      'markdown-strong': '#bc5215',
      'markdown-text': '#100f0f',
      'syntax-comment': '#6f6e69',
      'syntax-constant': '#5e409d',
      'syntax-keyword': '#66800b',
      'syntax-object': '#205ea6',
      'syntax-operator': '#6f6e69',
      'syntax-primitive': '#bc5215',
      'syntax-property': '#24837b',
      'syntax-punctuation': '#6f6e69',
      'syntax-string': '#24837b',
      'syntax-type': '#ad8301',
      'syntax-variable': '#205ea6',
      'text-weak': '#6f6e69',
    },
    palette: {
      accent: '#bc5215',
      error: '#af3029',
      info: '#24837b',
      ink: '#100f0f',
      neutral: '#fffcf0',
      primary: '#205ea6',
      success: '#66800b',
      warning: '#bc5215',
    },
  },
  'github-dark': {
    bg: '#0d1117',
    displayName: 'GitHub Dark',
    fg: '#c9d1d9',
    mode: 'dark',
    name: 'opencode:github',
    overrides: {
      'markdown-block-quote': '#8b949e',
      'markdown-code': '#ff7b72',
      'markdown-code-block': '#c9d1d9',
      'markdown-emph': '#e3b341',
      'markdown-heading': '#58a6ff',
      'markdown-horizontal-rule': '#30363d',
      'markdown-image': '#58a6ff',
      'markdown-image-text': '#39c5cf',
      'markdown-link': '#58a6ff',
      'markdown-link-text': '#39c5cf',
      'markdown-list-enumeration': '#39c5cf',
      'markdown-list-item': '#58a6ff',
      'markdown-strong': '#d29922',
      'markdown-text': '#c9d1d9',
      'syntax-comment': '#8b949e',
      'syntax-constant': '#58a6ff',
      'syntax-keyword': '#ff7b72',
      'syntax-object': '#d29922',
      'syntax-operator': '#ff7b72',
      'syntax-primitive': '#bc8cff',
      'syntax-property': '#39c5cf',
      'syntax-punctuation': '#c9d1d9',
      'syntax-string': '#39c5cf',
      'syntax-type': '#d29922',
      'syntax-variable': '#d29922',
      'text-weak': '#8b949e',
    },
    palette: {
      accent: '#39c5cf',
      error: '#f85149',
      info: '#d29922',
      ink: '#c9d1d9',
      neutral: '#0d1117',
      primary: '#58a6ff',
      success: '#3fb950',
      warning: '#e3b341',
    },
  },
  'github-light': {
    bg: '#ffffff',
    displayName: 'GitHub Light',
    fg: '#24292f',
    mode: 'light',
    name: 'opencode:github',
    overrides: {
      'markdown-block-quote': '#57606a',
      'markdown-code': '#bf3989',
      'markdown-code-block': '#24292f',
      'markdown-emph': '#9a6700',
      'markdown-heading': '#0969da',
      'markdown-horizontal-rule': '#d0d7de',
      'markdown-image': '#0969da',
      'markdown-image-text': '#1b7c83',
      'markdown-link': '#0969da',
      'markdown-link-text': '#1b7c83',
      'markdown-list-enumeration': '#1b7c83',
      'markdown-list-item': '#0969da',
      'markdown-strong': '#bc4c00',
      'markdown-text': '#24292f',
      'syntax-comment': '#57606a',
      'syntax-constant': '#1b7c83',
      'syntax-keyword': '#cf222e',
      'syntax-object': '#bc4c00',
      'syntax-operator': '#cf222e',
      'syntax-primitive': '#8250df',
      'syntax-property': '#1b7c83',
      'syntax-punctuation': '#24292f',
      'syntax-string': '#0969da',
      'syntax-type': '#bc4c00',
      'syntax-variable': '#bc4c00',
      'text-weak': '#57606a',
    },
    palette: {
      accent: '#1b7c83',
      error: '#cf222e',
      info: '#bc4c00',
      ink: '#24292f',
      neutral: '#ffffff',
      primary: '#0969da',
      success: '#1a7f37',
      warning: '#9a6700',
    },
  },
  'gruvbox-dark': {
    bg: '#282828',
    displayName: 'Gruvbox Dark',
    fg: '#ebdbb2',
    mode: 'dark',
    name: 'opencode:gruvbox',
    overrides: {
      'syntax-comment': '#928374',
      'syntax-constant': '#d3869b',
      'syntax-keyword': '#fb4934',
      'syntax-primitive': '#83a598',
    },
    palette: {
      accent: '#fb4934',
      diffAdd: '#b8bb26',
      diffDelete: '#fb4934',
      error: '#fb4934',
      info: '#d3869b',
      ink: '#ebdbb2',
      neutral: '#282828',
      primary: '#83a598',
      success: '#b8bb26',
      warning: '#fabd2f',
    },
  },
  'gruvbox-light': {
    bg: '#fbf1c7',
    displayName: 'Gruvbox Light',
    fg: '#3c3836',
    mode: 'light',
    name: 'opencode:gruvbox',
    overrides: {
      'syntax-comment': '#928374',
      'syntax-constant': '#8f3f71',
      'syntax-keyword': '#9d0006',
      'syntax-primitive': '#076678',
    },
    palette: {
      accent: '#9d0006',
      diffAdd: '#79740e',
      diffDelete: '#9d0006',
      error: '#9d0006',
      info: '#8f3f71',
      ink: '#3c3836',
      neutral: '#fbf1c7',
      primary: '#076678',
      success: '#79740e',
      warning: '#b57614',
    },
  },
  'kanagawa-dark': {
    bg: '#1f1f28',
    displayName: 'Kanagawa Dark',
    fg: '#dcd7ba',
    mode: 'dark',
    name: 'opencode:kanagawa',
    overrides: {
      'markdown-block-quote': '#727169',
      'markdown-code': '#98bb6c',
      'markdown-code-block': '#dcd7ba',
      'markdown-emph': '#c38d9d',
      'markdown-heading': '#957fb8',
      'markdown-horizontal-rule': '#727169',
      'markdown-image': '#7e9cd8',
      'markdown-image-text': '#76946a',
      'markdown-link': '#7e9cd8',
      'markdown-link-text': '#76946a',
      'markdown-list-enumeration': '#76946a',
      'markdown-list-item': '#7e9cd8',
      'markdown-strong': '#d7a657',
      'markdown-text': '#dcd7ba',
      'syntax-comment': '#727169',
      'syntax-constant': '#d7a657',
      'syntax-keyword': '#957fb8',
      'syntax-object': '#dcd7ba',
      'syntax-operator': '#d27e99',
      'syntax-primitive': '#7e9cd8',
      'syntax-property': '#76946a',
      'syntax-punctuation': '#dcd7ba',
      'syntax-string': '#98bb6c',
      'syntax-type': '#c38d9d',
      'syntax-variable': '#dcd7ba',
      'text-weak': '#727169',
    },
    palette: {
      accent: '#d27e99',
      diffAdd: '#a9d977',
      diffDelete: '#f24a4a',
      error: '#e82424',
      info: '#76946a',
      ink: '#dcd7ba',
      neutral: '#1f1f28',
      primary: '#7e9cd8',
      success: '#98bb6c',
      warning: '#d7a657',
    },
  },
  'kanagawa-light': {
    bg: '#f2e9de',
    displayName: 'Kanagawa Light',
    fg: '#54433a',
    mode: 'light',
    name: 'opencode:kanagawa',
    overrides: {
      'markdown-block-quote': '#9e9389',
      'markdown-code': '#98bb6c',
      'markdown-code-block': '#54433a',
      'markdown-emph': '#c38d9d',
      'markdown-heading': '#957fb8',
      'markdown-horizontal-rule': '#9e9389',
      'markdown-image': '#2d4f67',
      'markdown-image-text': '#76946a',
      'markdown-link': '#2d4f67',
      'markdown-link-text': '#76946a',
      'markdown-list-enumeration': '#76946a',
      'markdown-list-item': '#2d4f67',
      'markdown-strong': '#d7a657',
      'markdown-text': '#54433a',
      'syntax-comment': '#9e9389',
      'syntax-constant': '#d7a657',
      'syntax-keyword': '#957fb8',
      'syntax-object': '#54433a',
      'syntax-operator': '#d27e99',
      'syntax-primitive': '#2d4f67',
      'syntax-property': '#76946a',
      'syntax-punctuation': '#54433a',
      'syntax-string': '#98bb6c',
      'syntax-type': '#c38d9d',
      'syntax-variable': '#54433a',
      'text-weak': '#9e9389',
    },
    palette: {
      accent: '#d27e99',
      diffAdd: '#89af5b',
      diffDelete: '#d61f1f',
      error: '#e82424',
      info: '#76946a',
      ink: '#54433a',
      neutral: '#f2e9de',
      primary: '#2d4f67',
      success: '#98bb6c',
      warning: '#d7a657',
    },
  },
  'lucent-orng-dark': {
    bg: '#2a1a15',
    displayName: 'Lucent Orng Dark',
    fg: '#eeeeee',
    mode: 'dark',
    name: 'opencode:lucent-orng',
    overrides: {
      'markdown-block-quote': '#fff7f1',
      'markdown-code': '#6ba1e6',
      'markdown-code-block': '#eeeeee',
      'markdown-emph': '#e5c07b',
      'markdown-heading': '#ec5b2b',
      'markdown-horizontal-rule': '#808080',
      'markdown-image': '#ec5b2b',
      'markdown-image-text': '#56b6c2',
      'markdown-link': '#ec5b2b',
      'markdown-link-text': '#56b6c2',
      'markdown-list-enumeration': '#56b6c2',
      'markdown-list-item': '#ec5b2b',
      'markdown-strong': '#ee7948',
      'markdown-text': '#eeeeee',
      'syntax-comment': '#808080',
      'syntax-constant': '#fff7f1',
      'syntax-keyword': '#ec5b2b',
      'syntax-object': '#e06c75',
      'syntax-operator': '#56b6c2',
      'syntax-primitive': '#ee7948',
      'syntax-property': '#56b6c2',
      'syntax-punctuation': '#eeeeee',
      'syntax-string': '#6ba1e6',
      'syntax-type': '#e5c07b',
      'syntax-variable': '#e06c75',
      'text-weak': '#808080',
    },
    palette: {
      accent: '#fff7f1',
      diffDelete: '#e26a75',
      error: '#e06c75',
      info: '#56b6c2',
      ink: '#eeeeee',
      neutral: '#2a1a15',
      primary: '#ec5b2b',
      success: '#6ba1e6',
      warning: '#ec5b2b',
    },
  },
  'lucent-orng-light': {
    bg: '#fff5f0',
    displayName: 'Lucent Orng Light',
    fg: '#1a1a1a',
    mode: 'light',
    name: 'opencode:lucent-orng',
    overrides: {
      'markdown-block-quote': '#b0851f',
      'markdown-code': '#0062d1',
      'markdown-code-block': '#1a1a1a',
      'markdown-emph': '#b0851f',
      'markdown-heading': '#ec5b2b',
      'markdown-horizontal-rule': '#8a8a8a',
      'markdown-image': '#ec5b2b',
      'markdown-image-text': '#318795',
      'markdown-link': '#ec5b2b',
      'markdown-link-text': '#318795',
      'markdown-list-enumeration': '#318795',
      'markdown-list-item': '#ec5b2b',
      'markdown-strong': '#ec5b2b',
      'markdown-text': '#1a1a1a',
      'syntax-comment': '#8a8a8a',
      'syntax-constant': '#ec5b2b',
      'syntax-keyword': '#ec5b2b',
      'syntax-object': '#d1383d',
      'syntax-operator': '#318795',
      'syntax-primitive': '#c94d24',
      'syntax-property': '#318795',
      'syntax-punctuation': '#1a1a1a',
      'syntax-string': '#0062d1',
      'syntax-type': '#b0851f',
      'syntax-variable': '#d1383d',
      'text-weak': '#8a8a8a',
    },
    palette: {
      accent: '#c94d24',
      diffDelete: '#f52a65',
      error: '#d1383d',
      info: '#318795',
      ink: '#1a1a1a',
      neutral: '#fff5f0',
      primary: '#ec5b2b',
      success: '#0062d1',
      warning: '#ec5b2b',
    },
  },
  'material-dark': {
    bg: '#263238',
    displayName: 'Material Dark',
    fg: '#eeffff',
    mode: 'dark',
    name: 'opencode:material',
    overrides: {
      'markdown-block-quote': '#546e7a',
      'markdown-code': '#c3e88d',
      'markdown-code-block': '#eeffff',
      'markdown-emph': '#ffcb6b',
      'markdown-heading': '#82aaff',
      'markdown-horizontal-rule': '#37474f',
      'markdown-image': '#89ddff',
      'markdown-image-text': '#c792ea',
      'markdown-link': '#89ddff',
      'markdown-link-text': '#c792ea',
      'markdown-list-enumeration': '#89ddff',
      'markdown-list-item': '#82aaff',
      'markdown-strong': '#ffcb6b',
      'markdown-text': '#eeffff',
      'syntax-comment': '#546e7a',
      'syntax-constant': '#ffcb6b',
      'syntax-keyword': '#c792ea',
      'syntax-object': '#eeffff',
      'syntax-operator': '#89ddff',
      'syntax-primitive': '#82aaff',
      'syntax-property': '#c792ea',
      'syntax-punctuation': '#eeffff',
      'syntax-string': '#c3e88d',
      'syntax-type': '#ffcb6b',
      'syntax-variable': '#eeffff',
      'text-weak': '#546e7a',
    },
    palette: {
      accent: '#89ddff',
      error: '#f07178',
      info: '#ffcb6b',
      ink: '#eeffff',
      interactive: '#89ddff',
      neutral: '#263238',
      primary: '#82aaff',
      success: '#c3e88d',
      warning: '#ffcb6b',
    },
  },
  'material-light': {
    bg: '#fafafa',
    displayName: 'Material Light',
    fg: '#263238',
    mode: 'light',
    name: 'opencode:material',
    overrides: {
      'markdown-block-quote': '#90a4ae',
      'markdown-code': '#91b859',
      'markdown-code-block': '#263238',
      'markdown-emph': '#ffb300',
      'markdown-heading': '#6182b8',
      'markdown-horizontal-rule': '#e0e0e0',
      'markdown-image': '#39adb5',
      'markdown-image-text': '#7c4dff',
      'markdown-link': '#39adb5',
      'markdown-link-text': '#7c4dff',
      'markdown-list-enumeration': '#39adb5',
      'markdown-list-item': '#6182b8',
      'markdown-strong': '#f4511e',
      'markdown-text': '#263238',
      'syntax-comment': '#90a4ae',
      'syntax-constant': '#f4511e',
      'syntax-keyword': '#7c4dff',
      'syntax-object': '#263238',
      'syntax-operator': '#39adb5',
      'syntax-primitive': '#6182b8',
      'syntax-property': '#7c4dff',
      'syntax-punctuation': '#263238',
      'syntax-string': '#91b859',
      'syntax-type': '#ffb300',
      'syntax-variable': '#263238',
      'text-weak': '#90a4ae',
    },
    palette: {
      accent: '#39adb5',
      error: '#e53935',
      info: '#f4511e',
      ink: '#263238',
      interactive: '#39adb5',
      neutral: '#fafafa',
      primary: '#6182b8',
      success: '#91b859',
      warning: '#ffb300',
    },
  },
  'matrix-dark': {
    bg: '#0a0e0a',
    displayName: 'Matrix Dark',
    fg: '#62ff94',
    mode: 'dark',
    name: 'opencode:matrix',
    overrides: {
      'markdown-block-quote': '#8ca391',
      'markdown-code': '#1cc24b',
      'markdown-code-block': '#62ff94',
      'markdown-emph': '#ffa83d',
      'markdown-heading': '#00efff',
      'markdown-horizontal-rule': '#8ca391',
      'markdown-image': '#30b3ff',
      'markdown-image-text': '#24f6d9',
      'markdown-link': '#30b3ff',
      'markdown-link-text': '#24f6d9',
      'markdown-list-enumeration': '#24f6d9',
      'markdown-list-item': '#30b3ff',
      'markdown-strong': '#e6ff57',
      'markdown-text': '#62ff94',
      'syntax-comment': '#8ca391',
      'syntax-constant': '#ffa83d',
      'syntax-keyword': '#c770ff',
      'syntax-object': '#62ff94',
      'syntax-operator': '#24f6d9',
      'syntax-primitive': '#30b3ff',
      'syntax-property': '#24f6d9',
      'syntax-punctuation': '#62ff94',
      'syntax-string': '#1cc24b',
      'syntax-type': '#e6ff57',
      'syntax-variable': '#62ff94',
      'text-weak': '#8ca391',
    },
    palette: {
      accent: '#c770ff',
      diffAdd: '#77ffaf',
      diffDelete: '#ff7171',
      error: '#ff4b4b',
      info: '#30b3ff',
      ink: '#62ff94',
      interactive: '#30b3ff',
      neutral: '#0a0e0a',
      primary: '#2eff6a',
      success: '#62ff94',
      warning: '#e6ff57',
    },
  },
  'matrix-light': {
    bg: '#eef3ea',
    displayName: 'Matrix Light',
    fg: '#203022',
    mode: 'light',
    name: 'opencode:matrix',
    overrides: {
      'markdown-block-quote': '#748476',
      'markdown-code': '#1cc24b',
      'markdown-code-block': '#203022',
      'markdown-emph': '#ffa83d',
      'markdown-heading': '#24f6d9',
      'markdown-horizontal-rule': '#748476',
      'markdown-image': '#30b3ff',
      'markdown-image-text': '#24f6d9',
      'markdown-link': '#30b3ff',
      'markdown-link-text': '#24f6d9',
      'markdown-list-enumeration': '#24f6d9',
      'markdown-list-item': '#30b3ff',
      'markdown-strong': '#e6ff57',
      'markdown-text': '#203022',
      'syntax-comment': '#748476',
      'syntax-constant': '#ffa83d',
      'syntax-keyword': '#c770ff',
      'syntax-object': '#203022',
      'syntax-operator': '#24f6d9',
      'syntax-primitive': '#30b3ff',
      'syntax-property': '#24f6d9',
      'syntax-punctuation': '#203022',
      'syntax-string': '#1cc24b',
      'syntax-type': '#e6ff57',
      'syntax-variable': '#203022',
      'text-weak': '#748476',
    },
    palette: {
      accent: '#c770ff',
      diffAdd: '#5dac7e',
      diffDelete: '#d53a3a',
      error: '#ff4b4b',
      info: '#30b3ff',
      ink: '#203022',
      interactive: '#30b3ff',
      neutral: '#eef3ea',
      primary: '#1cc24b',
      success: '#1cc24b',
      warning: '#e6ff57',
    },
  },
  'mercury-dark': {
    bg: '#171721',
    displayName: 'Mercury Dark',
    fg: '#dddde5',
    mode: 'dark',
    name: 'opencode:mercury',
    overrides: {
      'markdown-block-quote': '#9d9da8',
      'markdown-code': '#77c599',
      'markdown-code-block': '#dddde5',
      'markdown-emph': '#fc9b6f',
      'markdown-heading': '#ffffff',
      'markdown-horizontal-rule': '#b4b7c8',
      'markdown-image': '#8da4f5',
      'markdown-image-text': '#a7b6f8',
      'markdown-link': '#8da4f5',
      'markdown-link-text': '#a7b6f8',
      'markdown-list-enumeration': '#8da4f5',
      'markdown-list-item': '#ffffff',
      'markdown-strong': '#f4f5f9',
      'markdown-text': '#dddde5',
      'syntax-comment': '#9d9da8',
      'syntax-constant': '#fc9b6f',
      'syntax-keyword': '#8da4f5',
      'syntax-object': '#77becf',
      'syntax-operator': '#8da4f5',
      'syntax-primitive': '#8da4f5',
      'syntax-property': '#a7b6f8',
      'syntax-punctuation': '#dddde5',
      'syntax-string': '#77c599',
      'syntax-type': '#77becf',
      'syntax-variable': '#77becf',
      'text-weak': '#9d9da8',
    },
    palette: {
      accent: '#8da4f5',
      error: '#fc92b4',
      info: '#77becf',
      ink: '#dddde5',
      neutral: '#171721',
      primary: '#8da4f5',
      success: '#77c599',
      warning: '#fc9b6f',
    },
  },
  'mercury-light': {
    bg: '#ffffff',
    displayName: 'Mercury Light',
    fg: '#363644',
    mode: 'light',
    name: 'opencode:mercury',
    overrides: {
      'markdown-block-quote': '#70707d',
      'markdown-code': '#036e43',
      'markdown-code-block': '#363644',
      'markdown-emph': '#a44200',
      'markdown-heading': '#1e1e2a',
      'markdown-horizontal-rule': '#707393',
      'markdown-image': '#465bd1',
      'markdown-image-text': '#5266eb',
      'markdown-link': '#465bd1',
      'markdown-link-text': '#5266eb',
      'markdown-list-enumeration': '#5266eb',
      'markdown-list-item': '#1e1e2a',
      'markdown-strong': '#1e1e2a',
      'markdown-text': '#363644',
      'syntax-comment': '#70707d',
      'syntax-constant': '#a44200',
      'syntax-keyword': '#465bd1',
      'syntax-object': '#007f95',
      'syntax-operator': '#465bd1',
      'syntax-primitive': '#5266eb',
      'syntax-property': '#5266eb',
      'syntax-punctuation': '#363644',
      'syntax-string': '#036e43',
      'syntax-type': '#007f95',
      'syntax-variable': '#007f95',
      'text-weak': '#70707d',
    },
    palette: {
      accent: '#8da4f5',
      error: '#b0175f',
      info: '#007f95',
      ink: '#363644',
      interactive: '#465bd1',
      neutral: '#ffffff',
      primary: '#5266eb',
      success: '#036e43',
      warning: '#a44200',
    },
  },
  'monokai-dark': {
    bg: '#272822',
    displayName: 'Monokai Dark',
    fg: '#f8f8f2',
    mode: 'dark',
    name: 'opencode:monokai',
    overrides: {
      'syntax-comment': '#75715e',
      'syntax-constant': '#ae81ff',
      'syntax-keyword': '#f92672',
      'syntax-primitive': '#a6e22e',
      'syntax-property': '#66d9ef',
      'syntax-string': '#e6db74',
    },
    palette: {
      accent: '#f92672',
      diffAdd: '#4d7f2a',
      diffDelete: '#f4477c',
      error: '#f92672',
      info: '#66d9ef',
      ink: '#f8f8f2',
      neutral: '#272822',
      primary: '#ae81ff',
      success: '#a6e22e',
      warning: '#fd971f',
    },
  },
  'monokai-light': {
    bg: '#fdf8ec',
    displayName: 'Monokai Light',
    fg: '#292318',
    mode: 'light',
    name: 'opencode:monokai',
    overrides: {
      'syntax-comment': '#8a816f',
      'syntax-constant': '#9b5fe0',
      'syntax-keyword': '#d9487c',
      'syntax-primitive': '#3c8d2f',
      'syntax-property': '#1f88c8',
      'syntax-string': '#8a6500',
    },
    palette: {
      accent: '#d9487c',
      diffAdd: '#bfe7a3',
      diffDelete: '#f6a3ae',
      error: '#e54b4b',
      info: '#2d9ad7',
      ink: '#292318',
      neutral: '#fdf8ec',
      primary: '#bf7bff',
      success: '#4fb54b',
      warning: '#f1a948',
    },
  },
  'nightowl-dark': {
    bg: '#011627',
    displayName: 'Night Owl Dark',
    fg: '#d6deeb',
    mode: 'dark',
    name: 'opencode:nightowl',
    overrides: {
      'syntax-comment': '#637777',
      'syntax-constant': '#f78c6c',
      'syntax-keyword': '#c792ea',
      'syntax-primitive': '#82aaff',
      'syntax-string': '#ecc48d',
    },
    palette: {
      accent: '#f78c6c',
      diffAdd: '#c5e478',
      diffDelete: '#ef5350',
      error: '#ef5350',
      info: '#82aaff',
      ink: '#d6deeb',
      neutral: '#011627',
      primary: '#82aaff',
      success: '#c5e478',
      warning: '#ecc48d',
    },
  },
  'nightowl-light': {
    bg: '#f0f0f0',
    displayName: 'Night Owl Light',
    fg: '#403f53',
    mode: 'light',
    name: 'opencode:nightowl',
    overrides: {
      'syntax-comment': '#7a8181',
      'syntax-constant': '#c96765',
      'syntax-keyword': '#994cc3',
      'syntax-primitive': '#4876d6',
    },
    palette: {
      accent: '#aa0982',
      diffAdd: '#2aa298',
      diffDelete: '#de3d3b',
      error: '#de3d3b',
      info: '#4876d6',
      ink: '#403f53',
      neutral: '#f0f0f0',
      primary: '#4876d6',
      success: '#2aa298',
      warning: '#c96765',
    },
  },
  'nord-dark': {
    bg: '#2e3440',
    displayName: 'Nord Dark',
    fg: '#e5e9f0',
    mode: 'dark',
    name: 'opencode:nord',
    overrides: {
      'syntax-comment': '#616e88',
      'syntax-constant': '#b48ead',
      'syntax-keyword': '#81a1c1',
      'syntax-primitive': '#88c0d0',
    },
    palette: {
      accent: '#d57780',
      diffAdd: '#81a1c1',
      diffDelete: '#bf616a',
      error: '#bf616a',
      info: '#81a1c1',
      ink: '#e5e9f0',
      neutral: '#2e3440',
      primary: '#88c0d0',
      success: '#a3be8c',
      warning: '#d08770',
    },
  },
  'nord-light': {
    bg: '#eceff4',
    displayName: 'Nord Light',
    fg: '#2e3440',
    mode: 'light',
    name: 'opencode:nord',
    overrides: {
      'syntax-comment': '#6b7282',
      'syntax-constant': '#8d6886',
      'syntax-keyword': '#5e81ac',
      'syntax-primitive': '#5e81ac',
      'syntax-string': '#6f8758',
    },
    palette: {
      accent: '#bf616a',
      diffAdd: '#a3be8c',
      diffDelete: '#bf616a',
      error: '#bf616a',
      info: '#81a1c1',
      ink: '#2e3440',
      neutral: '#eceff4',
      primary: '#5e81ac',
      success: '#8fbcbb',
      warning: '#d08770',
    },
  },
  'oc-2-dark': {
    bg: '#1f1f1f',
    displayName: 'OC-2 Dark',
    fg: '#f1ece8',
    mode: 'dark',
    name: 'opencode:oc-2',
    overrides: {
      'border-weak-base': '#282828',
      'border-weaker-base': '#232323',
      'icon-base': '#7e7e7e',
      'icon-weak-base': '#343434',
      'surface-base': '#1c1c1c',
      'surface-base-hover': '#ffffff',
      'surface-critical-base': '#1f0603',
      'surface-interactive-weak': '#0d172b',
      'surface-raised-base': '#232323',
      'surface-raised-base-hover': '#282828',
      'surface-success-base': '#022b00',
      'syntax-comment': '#8f8f8f',
      'syntax-constant': '#93e9f6',
      'syntax-critical': '#fab283',
      'syntax-diff-delete': '#fab283',
      'syntax-diff-unknown': '#edb2f1',
      'syntax-keyword': '#edb2f1',
      'syntax-primitive': '#8cb0ff',
      'syntax-property': '#fab283',
      'syntax-string': '#00ceb9',
      'syntax-type': '#fcd53a',
      'text-base': '#a0a0a0',
      'text-strong': '#ededed',
      'text-weak': '#707070',
      'text-weaker': '#505050',
    },
    palette: {
      diffAdd: '#c8ffc4',
      diffDelete: '#fc533a',
      error: '#fc533a',
      info: '#edb2f1',
      ink: '#f1ece8',
      interactive: '#034cff',
      neutral: '#1f1f1f',
      primary: '#fab283',
      success: '#12c905',
      warning: '#fcd53a',
    },
  },
  'oc-2-light': {
    bg: '#f7f7f7',
    displayName: 'OC-2 Light',
    fg: '#171311',
    mode: 'light',
    name: 'opencode:oc-2',
    overrides: {
      'border-weak-base': '#dbdbdb',
      'border-weaker-base': '#e8e8e8',
      'icon-base': '#8f8f8f',
      'icon-success-base': '#0abe00',
      'icon-weak-base': '#c7c7c7',
      'surface-base': '#f8f8f8',
      'surface-base-hover': '#000000',
      'surface-critical-base': '#fff2f0',
      'surface-interactive-weak': '#f5faff',
      'surface-raised-base': '#f3f3f3',
      'surface-raised-base-hover': '#ededed',
      'surface-success-base': '#e6ffe5',
      'syntax-comment': '#7a7a7a',
      'syntax-constant': '#007b80',
      'syntax-critical': '#ff8c00',
      'syntax-diff-delete': '#ff8c00',
      'syntax-diff-unknown': '#a753ae',
      'syntax-keyword': '#a753ae',
      'syntax-primitive': '#034cff',
      'syntax-property': '#a753ae',
      'syntax-string': '#00ceb9',
      'syntax-type': '#8a6f00',
      'text-base': '#6f6f6f',
      'text-strong': '#171717',
      'text-weak': '#8f8f8f',
      'text-weaker': '#c7c7c7',
    },
    palette: {
      diffAdd: '#9ff29a',
      diffDelete: '#fc533a',
      error: '#fc533a',
      info: '#a753ae',
      ink: '#171311',
      interactive: '#034cff',
      neutral: '#f7f7f7',
      primary: '#dcde8d',
      success: '#12c905',
      warning: '#ffdc17',
    },
  },
  'one-dark-dark': {
    bg: '#282c34',
    displayName: 'One Dark Dark',
    fg: '#abb2bf',
    mode: 'dark',
    name: 'opencode:one-dark',
    overrides: {
      'markdown-block-quote': '#5c6370',
      'markdown-code': '#98c379',
      'markdown-code-block': '#abb2bf',
      'markdown-emph': '#e5c07b',
      'markdown-heading': '#c678dd',
      'markdown-horizontal-rule': '#5c6370',
      'markdown-image': '#61afef',
      'markdown-image-text': '#56b6c2',
      'markdown-link': '#61afef',
      'markdown-link-text': '#56b6c2',
      'markdown-list-enumeration': '#56b6c2',
      'markdown-list-item': '#61afef',
      'markdown-strong': '#d19a66',
      'markdown-text': '#abb2bf',
      'syntax-comment': '#5c6370',
      'syntax-constant': '#d19a66',
      'syntax-keyword': '#c678dd',
      'syntax-object': '#e06c75',
      'syntax-operator': '#56b6c2',
      'syntax-primitive': '#61afef',
      'syntax-property': '#56b6c2',
      'syntax-punctuation': '#abb2bf',
      'syntax-string': '#98c379',
      'syntax-type': '#e5c07b',
      'syntax-variable': '#e06c75',
      'text-weak': '#5c6370',
    },
    palette: {
      accent: '#56b6c2',
      diffAdd: '#aad482',
      diffDelete: '#e8828b',
      error: '#e06c75',
      info: '#d19a66',
      ink: '#abb2bf',
      neutral: '#282c34',
      primary: '#61afef',
      success: '#98c379',
      warning: '#e5c07b',
    },
  },
  'one-dark-light': {
    bg: '#fafafa',
    displayName: 'One Dark Light',
    fg: '#383a42',
    mode: 'light',
    name: 'opencode:one-dark',
    overrides: {
      'markdown-block-quote': '#a0a1a7',
      'markdown-code': '#50a14f',
      'markdown-code-block': '#383a42',
      'markdown-emph': '#c18401',
      'markdown-heading': '#a626a4',
      'markdown-horizontal-rule': '#a0a1a7',
      'markdown-image': '#4078f2',
      'markdown-image-text': '#0184bc',
      'markdown-link': '#4078f2',
      'markdown-link-text': '#0184bc',
      'markdown-list-enumeration': '#0184bc',
      'markdown-list-item': '#4078f2',
      'markdown-strong': '#986801',
      'markdown-text': '#383a42',
      'syntax-comment': '#a0a1a7',
      'syntax-constant': '#986801',
      'syntax-keyword': '#a626a4',
      'syntax-object': '#e45649',
      'syntax-operator': '#0184bc',
      'syntax-primitive': '#4078f2',
      'syntax-property': '#0184bc',
      'syntax-punctuation': '#383a42',
      'syntax-string': '#50a14f',
      'syntax-type': '#c18401',
      'syntax-variable': '#e45649',
      'text-weak': '#a0a1a7',
    },
    palette: {
      accent: '#0184bc',
      diffAdd: '#489447',
      diffDelete: '#d65145',
      error: '#e45649',
      info: '#986801',
      ink: '#383a42',
      neutral: '#fafafa',
      primary: '#4078f2',
      success: '#50a14f',
      warning: '#c18401',
    },
  },
  'onedarkpro-dark': {
    bg: '#1e222a',
    displayName: 'One Dark Pro Dark',
    fg: '#abb2bf',
    mode: 'dark',
    name: 'opencode:onedarkpro',
    overrides: {
      'syntax-comment': '#5c6370',
      'syntax-constant': '#d19a66',
      'syntax-keyword': '#c678dd',
      'syntax-primitive': '#61afef',
    },
    palette: {
      accent: '#e06c75',
      diffAdd: '#4b815a',
      diffDelete: '#b2555f',
      error: '#e06c75',
      info: '#56b6c2',
      ink: '#abb2bf',
      neutral: '#1e222a',
      primary: '#61afef',
      success: '#98c379',
      warning: '#e5c07b',
    },
  },
  'onedarkpro-light': {
    bg: '#f5f6f8',
    displayName: 'One Dark Pro Light',
    fg: '#2b303b',
    mode: 'light',
    name: 'opencode:onedarkpro',
    overrides: {
      'syntax-comment': '#6a717d',
      'syntax-constant': '#986801',
      'syntax-keyword': '#a626a4',
      'syntax-primitive': '#4078f2',
    },
    palette: {
      accent: '#d85462',
      diffAdd: '#c2ebcf',
      diffDelete: '#f7c1c5',
      error: '#e06c75',
      info: '#61afef',
      ink: '#2b303b',
      neutral: '#f5f6f8',
      primary: '#528bff',
      success: '#4fa66d',
      warning: '#d19a66',
    },
  },
  'opencode-dark': {
    bg: '#0a0a0a',
    displayName: 'OpenCode Dark',
    fg: '#eeeeee',
    mode: 'dark',
    name: 'opencode:opencode',
    overrides: {
      'markdown-block-quote': '#e5c07b',
      'markdown-code': '#7fd88f',
      'markdown-code-block': '#eeeeee',
      'markdown-emph': '#e5c07b',
      'markdown-heading': '#9d7cd8',
      'markdown-horizontal-rule': '#808080',
      'markdown-image': '#fab283',
      'markdown-image-text': '#56b6c2',
      'markdown-link': '#fab283',
      'markdown-link-text': '#56b6c2',
      'markdown-list-enumeration': '#56b6c2',
      'markdown-list-item': '#fab283',
      'markdown-strong': '#f5a742',
      'markdown-text': '#eeeeee',
      'syntax-comment': '#808080',
      'syntax-constant': '#f5a742',
      'syntax-keyword': '#9d7cd8',
      'syntax-object': '#e06c75',
      'syntax-operator': '#56b6c2',
      'syntax-primitive': '#fab283',
      'syntax-property': '#56b6c2',
      'syntax-punctuation': '#eeeeee',
      'syntax-string': '#7fd88f',
      'syntax-type': '#e5c07b',
      'syntax-variable': '#e06c75',
      'text-weak': '#808080',
    },
    palette: {
      accent: '#9d7cd8',
      diffAdd: '#b8db87',
      diffDelete: '#e26a75',
      error: '#e06c75',
      info: '#56b6c2',
      ink: '#eeeeee',
      neutral: '#0a0a0a',
      primary: '#fab283',
      success: '#7fd88f',
      warning: '#f5a742',
    },
  },
  'opencode-light': {
    bg: '#ffffff',
    displayName: 'OpenCode Light',
    fg: '#1a1a1a',
    mode: 'light',
    name: 'opencode:opencode',
    overrides: {
      'markdown-block-quote': '#b0851f',
      'markdown-code': '#3d9a57',
      'markdown-code-block': '#1a1a1a',
      'markdown-emph': '#b0851f',
      'markdown-heading': '#d68c27',
      'markdown-horizontal-rule': '#8a8a8a',
      'markdown-image': '#3b7dd8',
      'markdown-image-text': '#318795',
      'markdown-link': '#3b7dd8',
      'markdown-link-text': '#318795',
      'markdown-list-enumeration': '#318795',
      'markdown-list-item': '#3b7dd8',
      'markdown-strong': '#d68c27',
      'markdown-text': '#1a1a1a',
      'syntax-comment': '#8a8a8a',
      'syntax-constant': '#d68c27',
      'syntax-keyword': '#d68c27',
      'syntax-object': '#d1383d',
      'syntax-operator': '#318795',
      'syntax-primitive': '#3b7dd8',
      'syntax-property': '#318795',
      'syntax-punctuation': '#1a1a1a',
      'syntax-string': '#3d9a57',
      'syntax-type': '#b0851f',
      'syntax-variable': '#d1383d',
      'text-weak': '#8a8a8a',
    },
    palette: {
      accent: '#d68c27',
      diffAdd: '#4db380',
      diffDelete: '#f52a65',
      error: '#d1383d',
      info: '#318795',
      ink: '#1a1a1a',
      neutral: '#ffffff',
      primary: '#3b7dd8',
      success: '#3d9a57',
      warning: '#d68c27',
    },
  },
  'orng-dark': {
    bg: '#0a0a0a',
    displayName: 'Orng Dark',
    fg: '#eeeeee',
    mode: 'dark',
    name: 'opencode:orng',
    overrides: {
      'markdown-block-quote': '#fff7f1',
      'markdown-code': '#6ba1e6',
      'markdown-code-block': '#eeeeee',
      'markdown-emph': '#e5c07b',
      'markdown-heading': '#ec5b2b',
      'markdown-horizontal-rule': '#808080',
      'markdown-image': '#ec5b2b',
      'markdown-image-text': '#56b6c2',
      'markdown-link': '#ec5b2b',
      'markdown-link-text': '#56b6c2',
      'markdown-list-enumeration': '#56b6c2',
      'markdown-list-item': '#ec5b2b',
      'markdown-strong': '#ee7948',
      'markdown-text': '#eeeeee',
      'syntax-comment': '#808080',
      'syntax-constant': '#fff7f1',
      'syntax-keyword': '#ec5b2b',
      'syntax-object': '#e06c75',
      'syntax-operator': '#56b6c2',
      'syntax-primitive': '#ee7948',
      'syntax-property': '#56b6c2',
      'syntax-punctuation': '#eeeeee',
      'syntax-string': '#6ba1e6',
      'syntax-type': '#e5c07b',
      'syntax-variable': '#e06c75',
      'text-weak': '#808080',
    },
    palette: {
      accent: '#fff7f1',
      diffDelete: '#e26a75',
      error: '#e06c75',
      info: '#56b6c2',
      ink: '#eeeeee',
      neutral: '#0a0a0a',
      primary: '#ec5b2b',
      success: '#6ba1e6',
      warning: '#ec5b2b',
    },
  },
  'orng-light': {
    bg: '#ffffff',
    displayName: 'Orng Light',
    fg: '#1a1a1a',
    mode: 'light',
    name: 'opencode:orng',
    overrides: {
      'markdown-block-quote': '#b0851f',
      'markdown-code': '#0062d1',
      'markdown-code-block': '#1a1a1a',
      'markdown-emph': '#b0851f',
      'markdown-heading': '#ec5b2b',
      'markdown-horizontal-rule': '#8a8a8a',
      'markdown-image': '#ec5b2b',
      'markdown-image-text': '#318795',
      'markdown-link': '#ec5b2b',
      'markdown-link-text': '#318795',
      'markdown-list-enumeration': '#318795',
      'markdown-list-item': '#ec5b2b',
      'markdown-strong': '#ec5b2b',
      'markdown-text': '#1a1a1a',
      'syntax-comment': '#8a8a8a',
      'syntax-constant': '#ec5b2b',
      'syntax-keyword': '#ec5b2b',
      'syntax-object': '#d1383d',
      'syntax-operator': '#318795',
      'syntax-primitive': '#c94d24',
      'syntax-property': '#318795',
      'syntax-punctuation': '#1a1a1a',
      'syntax-string': '#0062d1',
      'syntax-type': '#b0851f',
      'syntax-variable': '#d1383d',
      'text-weak': '#8a8a8a',
    },
    palette: {
      accent: '#c94d24',
      diffDelete: '#f52a65',
      error: '#d1383d',
      info: '#318795',
      ink: '#1a1a1a',
      neutral: '#ffffff',
      primary: '#ec5b2b',
      success: '#0062d1',
      warning: '#ec5b2b',
    },
  },
  'osaka-jade-dark': {
    bg: '#111c18',
    displayName: 'Osaka Jade Dark',
    fg: '#c1c497',
    mode: 'dark',
    name: 'opencode:osaka-jade',
    overrides: {
      'markdown-block-quote': '#53685b',
      'markdown-code': '#63b07a',
      'markdown-code-block': '#c1c497',
      'markdown-emph': '#d2689c',
      'markdown-heading': '#2dd5b7',
      'markdown-horizontal-rule': '#53685b',
      'markdown-image': '#8cd3cb',
      'markdown-image-text': '#549e6a',
      'markdown-link': '#8cd3cb',
      'markdown-link-text': '#549e6a',
      'markdown-list-enumeration': '#8cd3cb',
      'markdown-list-item': '#2dd5b7',
      'markdown-strong': '#c1c497',
      'markdown-text': '#c1c497',
      'syntax-comment': '#53685b',
      'syntax-constant': '#d2689c',
      'syntax-keyword': '#2dd5b7',
      'syntax-object': '#c1c497',
      'syntax-operator': '#459451',
      'syntax-primitive': '#509475',
      'syntax-property': '#549e6a',
      'syntax-punctuation': '#c1c497',
      'syntax-string': '#63b07a',
      'syntax-type': '#549e6a',
      'syntax-variable': '#c1c497',
      'text-weak': '#53685b',
    },
    palette: {
      accent: '#549e6a',
      diffAdd: '#63b07a',
      diffDelete: '#db9f9c',
      error: '#ff5345',
      info: '#2dd5b7',
      ink: '#c1c497',
      interactive: '#8cd3cb',
      neutral: '#111c18',
      primary: '#2dd5b7',
      success: '#549e6a',
      warning: '#e5c736',
    },
  },
  'osaka-jade-light': {
    bg: '#f6f5dd',
    displayName: 'Osaka Jade Light',
    fg: '#111c18',
    mode: 'light',
    name: 'opencode:osaka-jade',
    overrides: {
      'markdown-block-quote': '#53685b',
      'markdown-code': '#3d7a52',
      'markdown-code-block': '#111c18',
      'markdown-emph': '#a8527a',
      'markdown-heading': '#1faa90',
      'markdown-horizontal-rule': '#53685b',
      'markdown-image': '#1faa90',
      'markdown-image-text': '#3d7a52',
      'markdown-link': '#1faa90',
      'markdown-link-text': '#3d7a52',
      'markdown-list-enumeration': '#1faa90',
      'markdown-list-item': '#1faa90',
      'markdown-strong': '#111c18',
      'markdown-text': '#111c18',
      'syntax-comment': '#53685b',
      'syntax-constant': '#a8527a',
      'syntax-keyword': '#1faa90',
      'syntax-object': '#111c18',
      'syntax-operator': '#b5a020',
      'syntax-primitive': '#3d7560',
      'syntax-property': '#3d7a52',
      'syntax-punctuation': '#111c18',
      'syntax-string': '#3d7a52',
      'syntax-type': '#3d7a52',
      'syntax-variable': '#111c18',
      'text-weak': '#53685b',
    },
    palette: {
      accent: '#3d7a52',
      error: '#c7392d',
      info: '#1faa90',
      ink: '#111c18',
      neutral: '#f6f5dd',
      primary: '#1faa90',
      success: '#3d7a52',
      warning: '#b5a020',
    },
  },
  'palenight-dark': {
    bg: '#292d3e',
    displayName: 'Palenight Dark',
    fg: '#a6accd',
    mode: 'dark',
    name: 'opencode:palenight',
    overrides: {
      'markdown-block-quote': '#676e95',
      'markdown-code': '#c3e88d',
      'markdown-code-block': '#a6accd',
      'markdown-emph': '#ffcb6b',
      'markdown-heading': '#c792ea',
      'markdown-horizontal-rule': '#676e95',
      'markdown-image': '#82aaff',
      'markdown-image-text': '#89ddff',
      'markdown-link': '#82aaff',
      'markdown-link-text': '#89ddff',
      'markdown-list-enumeration': '#89ddff',
      'markdown-list-item': '#82aaff',
      'markdown-strong': '#f78c6c',
      'markdown-text': '#a6accd',
      'syntax-comment': '#676e95',
      'syntax-constant': '#f78c6c',
      'syntax-keyword': '#c792ea',
      'syntax-object': '#a6accd',
      'syntax-operator': '#89ddff',
      'syntax-primitive': '#82aaff',
      'syntax-property': '#89ddff',
      'syntax-punctuation': '#a6accd',
      'syntax-string': '#c3e88d',
      'syntax-type': '#ffcb6b',
      'syntax-variable': '#a6accd',
      'text-weak': '#676e95',
    },
    palette: {
      accent: '#89ddff',
      error: '#f07178',
      info: '#f78c6c',
      ink: '#a6accd',
      neutral: '#292d3e',
      primary: '#82aaff',
      success: '#c3e88d',
      warning: '#ffcb6b',
    },
  },
  'palenight-light': {
    bg: '#fafafa',
    displayName: 'Palenight Light',
    fg: '#292d3e',
    mode: 'light',
    name: 'opencode:palenight',
    overrides: {
      'markdown-block-quote': '#8796b0',
      'markdown-code': '#91b859',
      'markdown-code-block': '#292d3e',
      'markdown-emph': '#ffb300',
      'markdown-heading': '#a854f2',
      'markdown-horizontal-rule': '#8796b0',
      'markdown-image': '#4976eb',
      'markdown-image-text': '#00acc1',
      'markdown-link': '#4976eb',
      'markdown-link-text': '#00acc1',
      'markdown-list-enumeration': '#00acc1',
      'markdown-list-item': '#4976eb',
      'markdown-strong': '#f4511e',
      'markdown-text': '#292d3e',
      'syntax-comment': '#8796b0',
      'syntax-constant': '#f4511e',
      'syntax-keyword': '#a854f2',
      'syntax-object': '#292d3e',
      'syntax-operator': '#00acc1',
      'syntax-primitive': '#4976eb',
      'syntax-property': '#00acc1',
      'syntax-punctuation': '#292d3e',
      'syntax-string': '#91b859',
      'syntax-type': '#ffb300',
      'syntax-variable': '#292d3e',
      'text-weak': '#8796b0',
    },
    palette: {
      accent: '#00acc1',
      error: '#e53935',
      info: '#f4511e',
      ink: '#292d3e',
      neutral: '#fafafa',
      primary: '#4976eb',
      success: '#91b859',
      warning: '#ffb300',
    },
  },
  'rosepine-dark': {
    bg: '#191724',
    displayName: 'Rose Pine Dark',
    fg: '#e0def4',
    mode: 'dark',
    name: 'opencode:rosepine',
    overrides: {
      'markdown-block-quote': '#6e6a86',
      'markdown-code': '#31748f',
      'markdown-code-block': '#e0def4',
      'markdown-emph': '#f6c177',
      'markdown-heading': '#c4a7e7',
      'markdown-horizontal-rule': '#403d52',
      'markdown-image': '#9ccfd8',
      'markdown-image-text': '#ebbcba',
      'markdown-link': '#9ccfd8',
      'markdown-link-text': '#ebbcba',
      'markdown-list-enumeration': '#ebbcba',
      'markdown-list-item': '#9ccfd8',
      'markdown-strong': '#eb6f92',
      'markdown-text': '#e0def4',
      'syntax-comment': '#6e6a86',
      'syntax-constant': '#c4a7e7',
      'syntax-keyword': '#31748f',
      'syntax-object': '#e0def4',
      'syntax-operator': '#908caa',
      'syntax-primitive': '#ebbcba',
      'syntax-property': '#ebbcba',
      'syntax-punctuation': '#908caa',
      'syntax-string': '#f6c177',
      'syntax-type': '#9ccfd8',
      'syntax-variable': '#e0def4',
      'text-weak': '#6e6a86',
    },
    palette: {
      accent: '#ebbcba',
      error: '#eb6f92',
      info: '#9ccfd8',
      ink: '#e0def4',
      neutral: '#191724',
      primary: '#9ccfd8',
      success: '#31748f',
      warning: '#f6c177',
    },
  },
  'rosepine-light': {
    bg: '#faf4ed',
    displayName: 'Rose Pine Light',
    fg: '#575279',
    mode: 'light',
    name: 'opencode:rosepine',
    overrides: {
      'markdown-block-quote': '#9893a5',
      'markdown-code': '#286983',
      'markdown-code-block': '#575279',
      'markdown-emph': '#ea9d34',
      'markdown-heading': '#907aa9',
      'markdown-horizontal-rule': '#dfdad9',
      'markdown-image': '#31748f',
      'markdown-image-text': '#d7827e',
      'markdown-link': '#31748f',
      'markdown-link-text': '#d7827e',
      'markdown-list-enumeration': '#d7827e',
      'markdown-list-item': '#31748f',
      'markdown-strong': '#b4637a',
      'markdown-text': '#575279',
      'syntax-comment': '#9893a5',
      'syntax-constant': '#907aa9',
      'syntax-keyword': '#286983',
      'syntax-object': '#575279',
      'syntax-operator': '#797593',
      'syntax-primitive': '#d7827e',
      'syntax-property': '#d7827e',
      'syntax-punctuation': '#797593',
      'syntax-string': '#ea9d34',
      'syntax-type': '#56949f',
      'syntax-variable': '#575279',
      'text-weak': '#9893a5',
    },
    palette: {
      accent: '#d7827e',
      error: '#b4637a',
      info: '#56949f',
      ink: '#575279',
      neutral: '#faf4ed',
      primary: '#31748f',
      success: '#286983',
      warning: '#ea9d34',
    },
  },
  'shadesofpurple-dark': {
    bg: '#1a102b',
    displayName: 'Shades of Purple Dark',
    fg: '#f5f0ff',
    mode: 'dark',
    name: 'opencode:shadesofpurple',
    overrides: {
      'syntax-comment': '#b362ff',
      'syntax-constant': '#ff628c',
      'syntax-keyword': '#ff9d00',
      'syntax-primitive': '#fb94ff',
      'syntax-property': '#9effff',
      'syntax-string': '#a5ff90',
      'syntax-type': '#fad000',
    },
    palette: {
      accent: '#ff7ac6',
      diffAdd: '#53c39f',
      diffDelete: '#d85aa0',
      error: '#ff7ac6',
      info: '#7dd4ff',
      ink: '#f5f0ff',
      neutral: '#1a102b',
      primary: '#c792ff',
      success: '#7be0b0',
      warning: '#ffd580',
    },
  },
  'shadesofpurple-light': {
    bg: '#f7ebff',
    displayName: 'Shades of Purple Light',
    fg: '#3b2c59',
    mode: 'light',
    name: 'opencode:shadesofpurple',
    overrides: {
      'syntax-comment': '#8e4be3',
      'syntax-constant': '#e04d7a',
      'syntax-keyword': '#c45f00',
      'syntax-primitive': '#a13bd6',
      'syntax-property': '#008fb8',
      'syntax-string': '#2f8b32',
      'syntax-type': '#9d7a00',
    },
    palette: {
      accent: '#ff6bd5',
      diffAdd: '#c8f8da',
      diffDelete: '#ffc3ef',
      error: '#ff6bd5',
      info: '#62d4ff',
      ink: '#3b2c59',
      neutral: '#f7ebff',
      primary: '#7a5af8',
      success: '#3dd598',
      warning: '#f7c948',
    },
  },
  'solarized-dark': {
    bg: '#002b36',
    displayName: 'Solarized Dark',
    fg: '#93a1a1',
    mode: 'dark',
    name: 'opencode:solarized',
    overrides: {
      'syntax-comment': '#586e75',
      'syntax-constant': '#d33682',
      'syntax-keyword': '#859900',
      'syntax-primitive': '#268bd2',
      'syntax-property': '#268bd2',
      'syntax-string': '#2aa198',
    },
    palette: {
      accent: '#d33682',
      diffAdd: '#4c7654',
      diffDelete: '#c34b4b',
      error: '#dc322f',
      info: '#2aa198',
      ink: '#93a1a1',
      neutral: '#002b36',
      primary: '#6c71c4',
      success: '#859900',
      warning: '#b58900',
    },
  },
  'solarized-light': {
    bg: '#fdf6e3',
    displayName: 'Solarized Light',
    fg: '#586e75',
    mode: 'light',
    name: 'opencode:solarized',
    overrides: {
      'syntax-comment': '#657b83',
      'syntax-constant': '#d33682',
      'syntax-keyword': '#728600',
      'syntax-primitive': '#268bd2',
      'syntax-property': '#268bd2',
      'syntax-string': '#1f8f88',
    },
    palette: {
      accent: '#d33682',
      diffAdd: '#c6dc7a',
      diffDelete: '#f2a1a1',
      error: '#dc322f',
      info: '#2aa198',
      ink: '#586e75',
      neutral: '#fdf6e3',
      primary: '#268bd2',
      success: '#859900',
      warning: '#b58900',
    },
  },
  'synthwave84-dark': {
    bg: '#262335',
    displayName: "Synthwave '84 Dark",
    fg: '#ffffff',
    mode: 'dark',
    name: 'opencode:synthwave84',
    overrides: {
      'markdown-block-quote': '#848bbd',
      'markdown-code': '#72f1b8',
      'markdown-code-block': '#ffffff',
      'markdown-emph': '#fede5d',
      'markdown-heading': '#ff7edb',
      'markdown-horizontal-rule': '#495495',
      'markdown-image': '#36f9f6',
      'markdown-image-text': '#b084eb',
      'markdown-link': '#36f9f6',
      'markdown-link-text': '#b084eb',
      'markdown-list-enumeration': '#b084eb',
      'markdown-list-item': '#36f9f6',
      'markdown-strong': '#ff8b39',
      'markdown-text': '#ffffff',
      'syntax-comment': '#848bbd',
      'syntax-constant': '#b084eb',
      'syntax-keyword': '#ff7edb',
      'syntax-object': '#ffffff',
      'syntax-operator': '#ff7edb',
      'syntax-primitive': '#ff8b39',
      'syntax-property': '#b084eb',
      'syntax-punctuation': '#ffffff',
      'syntax-string': '#fede5d',
      'syntax-type': '#36f9f6',
      'syntax-variable': '#ffffff',
      'text-weak': '#848bbd',
    },
    palette: {
      accent: '#b084eb',
      diffAdd: '#97f1d8',
      diffDelete: '#ff5e5b',
      error: '#fe4450',
      info: '#ff8b39',
      ink: '#ffffff',
      neutral: '#262335',
      primary: '#36f9f6',
      success: '#72f1b8',
      warning: '#fede5d',
    },
  },
  'synthwave84-light': {
    bg: '#fafafa',
    displayName: "Synthwave '84 Light",
    fg: '#262335',
    mode: 'light',
    name: 'opencode:synthwave84',
    overrides: {
      'markdown-block-quote': '#5c5c8a',
      'markdown-code': '#4caf50',
      'markdown-code-block': '#262335',
      'markdown-emph': '#ff9800',
      'markdown-heading': '#e91e63',
      'markdown-horizontal-rule': '#e0e0e0',
      'markdown-image': '#00bcd4',
      'markdown-image-text': '#9c27b0',
      'markdown-link': '#00bcd4',
      'markdown-link-text': '#9c27b0',
      'markdown-list-enumeration': '#9c27b0',
      'markdown-list-item': '#00bcd4',
      'markdown-strong': '#ff5722',
      'markdown-text': '#262335',
      'syntax-comment': '#5c5c8a',
      'syntax-constant': '#9c27b0',
      'syntax-keyword': '#e91e63',
      'syntax-object': '#262335',
      'syntax-operator': '#e91e63',
      'syntax-primitive': '#ff5722',
      'syntax-property': '#9c27b0',
      'syntax-punctuation': '#262335',
      'syntax-string': '#ff9800',
      'syntax-type': '#00bcd4',
      'syntax-variable': '#262335',
      'text-weak': '#5c5c8a',
    },
    palette: {
      accent: '#9c27b0',
      error: '#f44336',
      info: '#ff5722',
      ink: '#262335',
      neutral: '#fafafa',
      primary: '#00bcd4',
      success: '#4caf50',
      warning: '#ff9800',
    },
  },
  'tokyonight-dark': {
    bg: '#1a1b26',
    displayName: 'Tokyonight Dark',
    fg: '#c0caf5',
    mode: 'dark',
    name: 'opencode:tokyonight',
    overrides: {
      'syntax-comment': '#565f89',
      'syntax-constant': '#ff9e64',
      'syntax-keyword': '#bb9af7',
      'syntax-primitive': '#7aa2f7',
      'syntax-property': '#7dcfff',
    },
    palette: {
      accent: '#ff9e64',
      diffAdd: '#41a6b5',
      diffDelete: '#c34043',
      error: '#f7768e',
      info: '#7dcfff',
      ink: '#c0caf5',
      neutral: '#1a1b26',
      primary: '#7aa2f7',
      success: '#9ece6a',
      warning: '#e0af68',
    },
  },
  'tokyonight-light': {
    bg: '#e1e2e7',
    displayName: 'Tokyonight Light',
    fg: '#273153',
    mode: 'light',
    name: 'opencode:tokyonight',
    overrides: {
      'syntax-comment': '#6b6f7a',
      'syntax-constant': '#b15c00',
      'syntax-keyword': '#9854f1',
      'syntax-primitive': '#1f6fd4',
      'syntax-property': '#007197',
    },
    palette: {
      accent: '#b15c00',
      diffAdd: '#4f8f7b',
      diffDelete: '#d05f7c',
      error: '#c94060',
      info: '#007197',
      ink: '#273153',
      neutral: '#e1e2e7',
      primary: '#2e7de9',
      success: '#587539',
      warning: '#8c6c3e',
    },
  },
  'vercel-dark': {
    bg: '#000000',
    displayName: 'Vercel Dark',
    fg: '#ededed',
    mode: 'dark',
    name: 'opencode:vercel',
    overrides: {
      'markdown-block-quote': '#878787',
      'markdown-code': '#63c46d',
      'markdown-code-block': '#ededed',
      'markdown-emph': '#f2a700',
      'markdown-heading': '#bf7af0',
      'markdown-horizontal-rule': '#454545',
      'markdown-image': '#0ac7ac',
      'markdown-image-text': '#50e3c2',
      'markdown-link': '#52a8ff',
      'markdown-link-text': '#0ac7ac',
      'markdown-list-enumeration': '#52a8ff',
      'markdown-list-item': '#ededed',
      'markdown-strong': '#f75590',
      'markdown-text': '#ededed',
      'syntax-comment': '#878787',
      'syntax-constant': '#f2a700',
      'syntax-keyword': '#f75590',
      'syntax-object': '#52a8ff',
      'syntax-operator': '#f75590',
      'syntax-primitive': '#bf7af0',
      'syntax-property': '#0ac7ac',
      'syntax-punctuation': '#ededed',
      'syntax-string': '#63c46d',
      'syntax-type': '#0ac7ac',
      'syntax-variable': '#52a8ff',
      'text-weak': '#878787',
    },
    palette: {
      accent: '#8e4ec6',
      diffAdd: '#63c46d',
      diffDelete: '#ff6166',
      error: '#e5484d',
      info: '#52a8ff',
      ink: '#ededed',
      interactive: '#52a8ff',
      neutral: '#000000',
      primary: '#0070f3',
      success: '#46a758',
      warning: '#ffb224',
    },
  },
  'vercel-light': {
    bg: '#ffffff',
    displayName: 'Vercel Light',
    fg: '#171717',
    mode: 'light',
    name: 'opencode:vercel',
    overrides: {
      'markdown-block-quote': '#666666',
      'markdown-code': '#46a758',
      'markdown-code-block': '#171717',
      'markdown-emph': '#ffb224',
      'markdown-heading': '#8e4ec6',
      'markdown-horizontal-rule': '#999999',
      'markdown-image': '#12a594',
      'markdown-image-text': '#12a594',
      'markdown-link': '#0070f3',
      'markdown-link-text': '#12a594',
      'markdown-list-enumeration': '#0070f3',
      'markdown-list-item': '#171717',
      'markdown-strong': '#e93d82',
      'markdown-text': '#171717',
      'syntax-comment': '#888888',
      'syntax-constant': '#ffb224',
      'syntax-keyword': '#e93d82',
      'syntax-object': '#0070f3',
      'syntax-operator': '#e93d82',
      'syntax-primitive': '#8e4ec6',
      'syntax-property': '#12a594',
      'syntax-punctuation': '#171717',
      'syntax-string': '#46a758',
      'syntax-type': '#12a594',
      'syntax-variable': '#0070f3',
      'text-weak': '#666666',
    },
    palette: {
      accent: '#8e4ec6',
      diffAdd: '#46a758',
      diffDelete: '#e5484d',
      error: '#dc3545',
      info: '#0070f3',
      ink: '#171717',
      neutral: '#ffffff',
      primary: '#0070f3',
      success: '#388e3c',
      warning: '#ff9500',
    },
  },
  'vesper-dark': {
    bg: '#101010',
    displayName: 'Vesper Dark',
    fg: '#ffffff',
    mode: 'dark',
    name: 'opencode:vesper',
    overrides: {
      'syntax-comment': '#8b8b8b',
      'syntax-constant': '#ffc799',
      'syntax-keyword': '#a0a0a0',
      'syntax-primitive': '#ffc799',
      'syntax-property': '#ffffff',
      'syntax-string': '#99ffe4',
      'syntax-type': '#ffc799',
    },
    palette: {
      accent: '#ff8080',
      diffAdd: '#99ffe4',
      diffDelete: '#ff8080',
      error: '#ff8080',
      info: '#ffc799',
      ink: '#ffffff',
      neutral: '#101010',
      primary: '#ffc799',
      success: '#99ffe4',
      warning: '#ffc799',
    },
  },
  'vesper-light': {
    bg: '#f0f0f0',
    displayName: 'Vesper Light',
    fg: '#101010',
    mode: 'light',
    name: 'opencode:vesper',
    overrides: {
      'syntax-comment': '#7a7a7a',
      'syntax-constant': '#8d541c',
      'syntax-keyword': '#6e6e6e',
      'syntax-primitive': '#8d541c',
      'syntax-property': '#101010',
      'syntax-string': '#117e69',
      'syntax-type': '#8d541c',
    },
    palette: {
      accent: '#b30000',
      diffAdd: '#99ffe4',
      diffDelete: '#ff8080',
      error: '#ff8080',
      info: '#ffc799',
      ink: '#101010',
      neutral: '#f0f0f0',
      primary: '#ffc799',
      success: '#99ffe4',
      warning: '#ffc799',
    },
  },
  'zenburn-dark': {
    bg: '#3f3f3f',
    displayName: 'Zenburn Dark',
    fg: '#dcdccc',
    mode: 'dark',
    name: 'opencode:zenburn',
    overrides: {
      'markdown-block-quote': '#9f9f9f',
      'markdown-code': '#7f9f7f',
      'markdown-code-block': '#dcdccc',
      'markdown-emph': '#e0cf9f',
      'markdown-heading': '#f0dfaf',
      'markdown-horizontal-rule': '#9f9f9f',
      'markdown-image': '#8cd0d3',
      'markdown-image-text': '#93e0e3',
      'markdown-link': '#8cd0d3',
      'markdown-link-text': '#93e0e3',
      'markdown-list-enumeration': '#93e0e3',
      'markdown-list-item': '#8cd0d3',
      'markdown-strong': '#dfaf8f',
      'markdown-text': '#dcdccc',
      'syntax-comment': '#7f9f7f',
      'syntax-constant': '#8fb28f',
      'syntax-keyword': '#f0dfaf',
      'syntax-object': '#dcdccc',
      'syntax-operator': '#f0dfaf',
      'syntax-primitive': '#8cd0d3',
      'syntax-property': '#93e0e3',
      'syntax-punctuation': '#dcdccc',
      'syntax-string': '#cc9393',
      'syntax-type': '#93e0e3',
      'syntax-variable': '#dcdccc',
      'text-weak': '#9f9f9f',
    },
    palette: {
      accent: '#93e0e3',
      diffAdd: '#8fb28f',
      diffDelete: '#dca3a3',
      error: '#cc9393',
      info: '#dfaf8f',
      ink: '#dcdccc',
      neutral: '#3f3f3f',
      primary: '#8cd0d3',
      success: '#7f9f7f',
      warning: '#f0dfaf',
    },
  },
  'zenburn-light': {
    bg: '#ffffef',
    displayName: 'Zenburn Light',
    fg: '#3f3f3f',
    mode: 'light',
    name: 'opencode:zenburn',
    overrides: {
      'markdown-block-quote': '#6f6f6f',
      'markdown-code': '#5f8f5f',
      'markdown-code-block': '#3f3f3f',
      'markdown-emph': '#8f8f5f',
      'markdown-heading': '#8f8f5f',
      'markdown-horizontal-rule': '#6f6f6f',
      'markdown-image': '#5f7f8f',
      'markdown-image-text': '#5f8f8f',
      'markdown-link': '#5f7f8f',
      'markdown-link-text': '#5f8f8f',
      'markdown-list-enumeration': '#5f8f8f',
      'markdown-list-item': '#5f7f8f',
      'markdown-strong': '#8f7f5f',
      'markdown-text': '#3f3f3f',
      'syntax-comment': '#5f7f5f',
      'syntax-constant': '#5f8f5f',
      'syntax-keyword': '#8f8f5f',
      'syntax-object': '#3f3f3f',
      'syntax-operator': '#8f8f5f',
      'syntax-primitive': '#5f7f8f',
      'syntax-property': '#5f8f8f',
      'syntax-punctuation': '#3f3f3f',
      'syntax-string': '#8f5f5f',
      'syntax-type': '#5f8f8f',
      'syntax-variable': '#3f3f3f',
      'text-weak': '#6f6f6f',
    },
    palette: {
      accent: '#5f8f8f',
      error: '#8f5f5f',
      info: '#8f7f5f',
      ink: '#3f3f3f',
      neutral: '#ffffef',
      primary: '#5f7f8f',
      success: '#5f8f5f',
      warning: '#8f8f5f',
    },
  },
}

export const OPENCODE_THEME_IDS: string[] = [
  'amoled-dark',
  'amoled-light',
  'aura-dark',
  'aura-light',
  'ayu-dark',
  'ayu-light',
  'carbonfox-dark',
  'carbonfox-light',
  'catppuccin-dark',
  'catppuccin-light',
  'catppuccin-frappe-dark',
  'catppuccin-frappe-light',
  'catppuccin-macchiato-dark',
  'catppuccin-macchiato-light',
  'cobalt2-dark',
  'cobalt2-light',
  'cursor-dark',
  'cursor-light',
  'dracula-dark',
  'dracula-light',
  'everforest-dark',
  'everforest-light',
  'flexoki-dark',
  'flexoki-light',
  'github-dark',
  'github-light',
  'gruvbox-dark',
  'gruvbox-light',
  'kanagawa-dark',
  'kanagawa-light',
  'lucent-orng-dark',
  'lucent-orng-light',
  'material-dark',
  'material-light',
  'matrix-dark',
  'matrix-light',
  'mercury-dark',
  'mercury-light',
  'monokai-dark',
  'monokai-light',
  'nightowl-dark',
  'nightowl-light',
  'nord-dark',
  'nord-light',
  'oc-2-dark',
  'oc-2-light',
  'one-dark-dark',
  'one-dark-light',
  'onedarkpro-dark',
  'onedarkpro-light',
  'opencode-dark',
  'opencode-light',
  'orng-dark',
  'orng-light',
  'osaka-jade-dark',
  'osaka-jade-light',
  'palenight-dark',
  'palenight-light',
  'rosepine-dark',
  'rosepine-light',
  'shadesofpurple-dark',
  'shadesofpurple-light',
  'solarized-dark',
  'solarized-light',
  'synthwave84-dark',
  'synthwave84-light',
  'tokyonight-dark',
  'tokyonight-light',
  'vercel-dark',
  'vercel-light',
  'vesper-dark',
  'vesper-light',
  'zenburn-dark',
  'zenburn-light',
]
