/* eslint-disable no-console, typescript/no-non-null-assertion, typescript/no-explicit-any */
import { writeFileSync } from 'node:fs'
import { type BundledTheme, bundledThemesInfo, createHighlighter } from 'shiki'

import type { Theme } from '../packages/aimux-config/src/types'

import { normalizeTheme } from '../packages/aimux-config/src/normalize-theme'

function stableStringify(value: any, indent: number): string {
  if (value === null || typeof value !== 'object') return JSON.stringify(value)
  if (Array.isArray(value)) {
    if (value.length === 0) return '[]'
    const pad = ' '.repeat(indent + 2)
    const closePad = ' '.repeat(indent)
    const items = value.map((v) => pad + stableStringify(v, indent + 2))
    return `[\n${items.join(',\n')},\n${closePad}]`
  }
  const keys = Object.keys(value).sort()
  if (keys.length === 0) return '{}'
  const pad = ' '.repeat(indent + 2)
  const closePad = ' '.repeat(indent)
  const entries = keys.map(
    (k) => `${pad}${JSON.stringify(k)}: ${stableStringify(value[k], indent + 2)}`
  )
  return `{\n${entries.join(',\n')},\n${closePad}}`
}

function emit(entries: Record<string, Theme>, headerComment: string): string {
  const lines: string[] = []
  lines.push('// @generated by scripts/generate-themes.ts. DO NOT EDIT.')
  lines.push(`// ${headerComment}`)
  lines.push('/* eslint-disable */')
  lines.push('')
  lines.push(`import type { Theme, ThemeId } from './types'`)
  lines.push('')
  lines.push('export const GENERATED_THEMES: Record<ThemeId, Theme> = {')
  const ids = Object.keys(entries).sort()
  for (const id of ids) {
    const theme = entries[id]!
    lines.push(`  ${JSON.stringify(id)}: ${stableStringify(theme, 2)},`)
  }
  lines.push('}')
  lines.push('')
  lines.push(
    'export const GENERATED_THEME_IDS: ThemeId[] = Object.keys(GENERATED_THEMES) as ThemeId[]'
  )
  lines.push('')
  return lines.join('\n')
}

async function main(): Promise<void> {
  const ids = bundledThemesInfo.map((t) => t.id as BundledTheme)
  console.log(`Loading ${ids.length} shiki themes…`)
  const h = await createHighlighter({ langs: [], themes: ids })
  const out: Record<string, Theme> = {}
  for (const info of bundledThemesInfo) {
    const raw = h.getTheme(info.id)
    out[info.id] = {
      ...normalizeTheme(raw),
      displayName: info.displayName,
    }
  }

  const header = `${ids.length} themes from shiki, normalized to aimux Theme shape`
  const configPath = 'packages/aimux-config/src/themes.generated.ts'
  writeFileSync(configPath, emit(out, header))
  console.log(`Wrote ${configPath}`)
}

void main()
