/* eslint-disable no-console, typescript/no-non-null-assertion, typescript/no-explicit-any */
import { mkdirSync, readdirSync, rmSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'
import { type BundledTheme, bundledThemesInfo, createHighlighter } from 'shiki'

import type { Theme } from '../packages/aimux-config/src/types'

import { normalizeTheme } from '../packages/aimux-config/src/normalize-theme'

function stableStringify(value: any, indent: number): string {
  if (value === null || typeof value !== 'object') return JSON.stringify(value)
  if (Array.isArray(value)) {
    if (value.length === 0) return '[]'
    const pad = ' '.repeat(indent + 2)
    const closePad = ' '.repeat(indent)
    const items = value.map((v) => pad + stableStringify(v, indent + 2))
    return `[\n${items.join(',\n')},\n${closePad}]`
  }
  const keys = Object.keys(value).sort()
  if (keys.length === 0) return '{}'
  const pad = ' '.repeat(indent + 2)
  const closePad = ' '.repeat(indent)
  const entries = keys.map(
    (k) => `${pad}${JSON.stringify(k)}: ${stableStringify(value[k], indent + 2)}`
  )
  return `{\n${entries.join(',\n')},\n${closePad}}`
}

function safeConstName(id: string): string {
  // e.g. 'catppuccin-mocha' -> 'catppuccinMocha', 'github-dark-high-contrast' -> 'githubDarkHighContrast'
  return id.replace(/-([a-z0-9])/g, (_, c: string) => c.toUpperCase()).replace(/[^a-zA-Z0-9]/g, '')
}

function emitThemeFile(theme: Theme): string {
  const lines: string[] = []
  lines.push('// @generated by scripts/generate-themes.ts. DO NOT EDIT.')
  lines.push('/* eslint-disable */')
  lines.push('')
  lines.push("import type { Theme } from '../../types'")
  lines.push('')
  lines.push(`export const theme: Theme = ${stableStringify(theme, 0)}`)
  lines.push('')
  return lines.join('\n')
}

function emitIndexFile(ids: string[]): string {
  const lines: string[] = []
  lines.push('// @generated by scripts/generate-themes.ts. DO NOT EDIT.')
  lines.push('/* eslint-disable */')
  lines.push('')
  lines.push("import type { Theme, ThemeId } from '../../types'")
  lines.push('')
  const sorted = [...ids].sort()
  for (const id of sorted) {
    lines.push(`import { theme as ${safeConstName(id)} } from './${id}'`)
  }
  lines.push('')
  lines.push('export const GENERATED_THEMES: Record<ThemeId, Theme> = {')
  for (const id of sorted) {
    lines.push(`  ${JSON.stringify(id)}: ${safeConstName(id)},`)
  }
  lines.push('}')
  lines.push('')
  lines.push(
    'export const GENERATED_THEME_IDS: ThemeId[] = Object.keys(GENERATED_THEMES) as ThemeId[]'
  )
  lines.push('')
  return lines.join('\n')
}

async function main(): Promise<void> {
  const ids = bundledThemesInfo.map((t) => t.id as BundledTheme)
  console.log(`Loading ${ids.length} shiki themes…`)
  const h = await createHighlighter({ langs: [], themes: ids })

  const outDir = 'packages/aimux-config/src/themes/generated'
  mkdirSync(outDir, { recursive: true })

  // Wipe the directory (except anything we don't own) so removed shiki themes
  // don't leave orphan files behind.
  for (const entry of readdirSync(outDir)) {
    rmSync(join(outDir, entry), { force: true })
  }

  for (const info of bundledThemesInfo) {
    const raw = h.getTheme(info.id)
    const theme: Theme = {
      ...normalizeTheme(raw),
      displayName: info.displayName,
    }
    writeFileSync(join(outDir, `${info.id}.ts`), emitThemeFile(theme))
  }
  writeFileSync(join(outDir, 'index.ts'), emitIndexFile(bundledThemesInfo.map((t) => t.id)))
  console.log(`Wrote ${ids.length} theme files + index to ${outDir}`)
}

void main()
