/* eslint-disable no-console, typescript/no-non-null-assertion */
import { writeFileSync } from 'node:fs'
import { type BundledTheme, bundledThemesInfo, createHighlighter } from 'shiki'

import { derivePalette, type PaletteColors } from './derive-palette'

interface ThemeEntry {
  colors: PaletteColors
  name: string
  type: 'dark' | 'light'
}

function emit(
  entries: Record<string, ThemeEntry>,
  headerComment: string,
  importPath: string
): string {
  const lines: string[] = []
  lines.push('// @generated by scripts/generate-themes.ts. DO NOT EDIT.')
  lines.push(`// ${headerComment}`)
  lines.push('')
  lines.push(`import type { ThemeColors, ThemeId } from '${importPath}'`)
  lines.push('')
  lines.push(
    "export const GENERATED_THEMES: Record<ThemeId, { name: string; type: 'dark' | 'light'; colors: ThemeColors }> = {"
  )
  const keys = Object.keys(entries).sort()
  for (const id of keys) {
    const e = entries[id]!
    lines.push(`  ${JSON.stringify(id)}: {`)
    lines.push('    colors: {')
    const colorKeys = Object.keys(e.colors).sort() as (keyof PaletteColors)[]
    for (const k of colorKeys) {
      lines.push(`      ${k}: ${JSON.stringify(e.colors[k])},`)
    }
    lines.push('    },')
    lines.push(`    name: ${JSON.stringify(e.name)},`)
    lines.push(`    type: ${JSON.stringify(e.type)},`)
    lines.push('  },')
  }
  lines.push('}')
  lines.push('')
  lines.push(
    'export const GENERATED_THEME_IDS: ThemeId[] = Object.keys(GENERATED_THEMES) as ThemeId[]'
  )
  lines.push('')
  return lines.join('\n')
}

async function main(): Promise<void> {
  const ids = bundledThemesInfo.map((t) => t.id as BundledTheme)
  console.log(`Loading ${ids.length} shiki themes…`)
  const h = await createHighlighter({ langs: [], themes: ids })
  const out: Record<string, ThemeEntry> = {}
  for (const info of bundledThemesInfo) {
    const t = h.getTheme(info.id)
    out[info.id] = { colors: derivePalette(t), name: info.displayName, type: info.type }
  }

  const header = `${ids.length} themes from shiki`
  const configPath = 'packages/aimux-config/src/themes.generated.ts'
  const runtimePath = 'src/ui/themes.generated.ts'

  writeFileSync(configPath, emit(out, header, './types'))
  writeFileSync(runtimePath, emit(out, header, './themes'))
  console.log(`Wrote ${configPath}`)
  console.log(`Wrote ${runtimePath}`)
}

void main()
